/**
 * moduleFieldDefinitions.ts — Definiciones de campos oficiales para los aplicativos de WAPPY
 * Usado por el Mapeador Universal de Columnas (Paralelo de Casillas).
 */

import { TargetFieldDef } from './columnMapperEngine';

// ─── 1. Perfil Sociodemográfico ──────────────────────────────────────────────
export const SOCIODEMOGRAFICO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre Completo',
    required: true,
    description: 'Nombres y apellidos completos del trabajador',
    synonyms: ['nombres', 'apellidos', 'nombrecompleto', 'colaborador', 'empleado', 'trabajador', 'nombresyapellidos', 'apellidosynombres'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Número de Identificación / Cédula',
    required: true,
    description: 'Cédula de ciudadanía, extranjería, PEP o PPT',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'numerocedula', 'dni', 'nodeidentificacion', 'nodedocumento', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Puesto de Trabajo',
    required: false,
    description: 'Cargo actual desempeñado en la empresa',
    synonyms: ['puesto', 'ocupacion', 'oficio', 'cargotrabajador', 'puestotrabajo', 'cargoactual'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino, Femenino u Otro',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaNacimiento',
    label: 'Fecha de Nacimiento',
    required: false,
    description: 'Formato YYYY-MM-DD o DD/MM/AAAA',
    synonyms: ['fnacimiento', 'fechanac', 'fechanacimiento', 'cumpleanos', 'natalicio'],
    type: 'date',
  },
  {
    key: 'estadoCivil',
    label: 'Estado Civil',
    required: false,
    description: 'Soltero, Casado, Unión libre, Separado, Viudo',
    synonyms: ['estadocivil', 'estadocivilactual'],
    type: 'string',
  },
  {
    key: 'nivelEscolaridad',
    label: 'Nivel de Escolaridad',
    required: false,
    description: 'Primaria, Bachiller, Técnico, Tecnólogo, Profesional, Posgrado',
    synonyms: ['escolaridad', 'estudios', 'gradoinstruccion', 'nivelacademico', 'titulacion'],
    type: 'string',
  },
  {
    key: 'telefono',
    label: 'Teléfono / Celular',
    required: false,
    description: 'Número de contacto móvil o fijo',
    synonyms: ['celular', 'tel', 'movil', 'telefonofijo', 'numerocelular', 'contacto'],
    type: 'string',
  },
  {
    key: 'correoElectronico',
    label: 'Correo Electrónico',
    required: false,
    description: 'Email corporativo o personal',
    synonyms: ['email', 'correo', 'mail', 'correopersonal', 'correocorporativo'],
    type: 'string',
  },
  {
    key: 'direccion',
    label: 'Dirección de Residencia',
    required: false,
    description: 'Dirección física de domicilio',
    synonyms: ['domicilio', 'residencia', 'direcciondomicilio'],
    type: 'string',
  },
  {
    key: 'barrio',
    label: 'Barrio',
    required: false,
    description: 'Barrio de residencia',
    synonyms: ['sector', 'barrioresidencia'],
    type: 'string',
  },
  {
    key: 'municipioDomicilio',
    label: 'Municipio / Ciudad',
    required: false,
    description: 'Ciudad de residencia habitual',
    synonyms: ['ciudad', 'municipio', 'poblacion'],
    type: 'string',
  },
  {
    key: 'estrato',
    label: 'Estrato Socioeconómico',
    required: false,
    description: 'Estrato de 1 a 6',
    synonyms: ['estratosocioeconomico'],
    type: 'string',
  },
  {
    key: 'vivienda',
    label: 'Tipo de Vivienda',
    required: false,
    description: 'Propia, Arrendada, Familiar, etc.',
    synonyms: ['tipovivienda', 'tenenciavivienda'],
    type: 'string',
  },
  {
    key: 'personasCargo',
    label: 'Personas a Cargo / Hijos',
    required: false,
    description: 'Cantidad de personas dependientes',
    synonyms: ['hijos', 'personascargo', 'dependientes', 'numhijos', 'numerohijos'],
    type: 'number',
  },
  {
    key: 'salario',
    label: 'Salario / Remuneración',
    required: false,
    description: 'Salario base o rango salarial',
    synonyms: ['sueldo', 'remuneracion', 'salariobasico', 'ingresos'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma?',
    required: false,
    description: 'Hábito de tabaquismo (Sí / No)',
    synonyms: ['fumador', 'cigarrillo', 'tabaco', 'consumotabaco'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'deporte',
    label: 'Actividad Física / Deporte',
    required: false,
    description: 'Frecuencia o tipo de ejercicio físico',
    synonyms: ['actividadfisica', 'ejercicio', 'practicadeporte'],
    type: 'string',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnósticos Médicos Previos',
    required: false,
    description: 'Antecedentes o patologías diagnosticadas',
    synonyms: ['diagnostico', 'patologia', 'enfermedades', 'antecedentes'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha Último Examen Médico',
    required: false,
    description: 'Fecha de valoración médica ocupacional',
    synonyms: ['fechaexamen', 'fechamedico', 'ultimoexamen', 'examenocupacional'],
    type: 'date',
  },
];

// ─── 2. Condiciones de Salud ────────────────────────────────────────────────
export const CONDICIONES_SALUD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Trabajador',
    required: true,
    description: 'Nombre y apellidos del colaborador',
    synonyms: ['trabajador', 'colaborador', 'empleado', 'nombresyapellidos', 'nombrecompleto', 'nombres', 'apellidos'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Identificación / Cédula',
    required: true,
    description: 'Número de documento de identidad',
    synonyms: ['cedula', 'cc', 'documento', 'numeroidentificacion', 'dni', 'nodeidentificacion', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo',
    required: false,
    description: 'Cargo u ocupación evaluada',
    synonyms: ['puesto', 'oficio', 'cargotrabajador', 'puestotrabajo'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino o Femenino',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha del Examen Médico',
    required: false,
    description: 'Fecha en que se practicó la evaluación ocupacional',
    synonyms: ['fecha', 'fechavaloracion', 'fechamedica', 'fechaexamen', 'fechadelexamen', 'ultimoexamen'],
    type: 'date',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnóstico Médico (CIE-10)',
    required: false,
    description: 'Código CIE-10 o descripción médica del diagnóstico',
    synonyms: ['diagnostico', 'cie10', 'patologia', 'hallazgo', 'enfermedad', 'diagnosticoprincipal', 'conceptomedico'],
    type: 'string',
  },
  {
    key: 'recomendacionesMedicas',
    label: 'Recomendaciones y Restricciones',
    required: false,
    description: 'Medidas médico-laborales preventivas, restricciones o correctivas',
    synonyms: ['restricciones', 'recomendaciones', 'medidas', 'indicaciones', 'restriccionesyrecomendaciones', 'recomendacion'],
    type: 'string',
  },
  {
    key: 'fechaSeguimiento',
    label: 'Fecha de Próximo Seguimiento',
    required: false,
    description: 'Fecha de control médico programada',
    synonyms: ['proximocontrol', 'seguimiento', 'fechavencimiento', 'fechaseguimiento', 'controlmedico'],
    type: 'date',
  },
  {
    key: 'peso',
    label: 'Peso (Kg)',
    required: false,
    description: 'Peso corporal del trabajador en kilogramos',
    synonyms: ['pesokg', 'pesocorporal', 'kg'],
    type: 'string',
  },
  {
    key: 'talla',
    label: 'Talla / Estatura (cm o m)',
    required: false,
    description: 'Estatura en centímetros o metros',
    synonyms: ['estatura', 'altura', 'cm', 'tallacm'],
    type: 'string',
  },
  {
    key: 'imc',
    label: 'Índice de Masa Corporal (IMC)',
    required: false,
    description: 'Valor o clasificación del IMC',
    synonyms: ['indicemasacorporal', 'masacorporal'],
    type: 'string',
  },
  {
    key: 'presionArterial',
    label: 'Presión Arterial (Tensión)',
    required: false,
    description: 'Cifras de tensión arterial (ej. 120/80)',
    synonyms: ['tension', 'tensionarterial', 'ta', 'pa'],
    type: 'string',
  },
  {
    key: 'frecuenciaCardiaca',
    label: 'Frecuencia Cardíaca (lpm)',
    required: false,
    description: 'Pulsaciones por minuto',
    synonyms: ['pulso', 'fc', 'latidos'],
    type: 'string',
  },
  {
    key: 'limitacionesBiomecanicas',
    label: 'Limitaciones Biomecánicas',
    required: false,
    description: 'Restricciones posturales, de carga o movimientos repetitivos',
    synonyms: ['limitacion', 'biomecanica', 'ergonomia', 'restriccionbiomecanica'],
    type: 'string',
  },
  {
    key: 'alergiasQuimicas',
    label: 'Alergias o Sustancias Químicas',
    required: false,
    description: 'Alergias a fármacos, látex, químicos u otros',
    synonyms: ['alergias', 'alergia', 'reacciones'],
    type: 'string',
  },
  {
    key: 'enfermedades',
    label: 'Enfermedades Comunes / Antecedentes',
    required: false,
    description: 'Hipertensión, diabetes u otras patologías crónicas',
    synonyms: ['antecedentespatologicos', 'enfermedadesprevias', 'patologias'],
    type: 'string',
  },
  {
    key: 'medicamentos',
    label: 'Medicamentos Habituales',
    required: false,
    description: 'Tratamientos farmacológicos actuales',
    synonyms: ['medicacion', 'farmacos', 'tratamiento'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma? (Hábito Tabaquismo)',
    required: false,
    description: 'Consumo de cigarrillo o tabaco (Sí / No)',
    synonyms: ['tabaquismo', 'fumador', 'cigarrillo'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
];

// ─── 3. Perfiles de Cargo ────────────────────────────────────────────────────
export const PERFILES_CARGO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombreCargo',
    label: 'Nombre del Cargo',
    required: true,
    description: 'Denominación oficial del cargo o puesto',
    synonyms: ['cargo', 'puesto', 'nombrepuesto', 'titulocargo', 'denominacion', 'puestodetrabajo', 'nombredelcargo'],
    type: 'string',
  },
  {
    key: 'area',
    label: 'Área / Departamento',
    required: false,
    description: 'Proceso, gerencia o departamento al que pertenece',
    synonyms: ['departamento', 'proceso', 'seccion', 'gerencia', 'unidad', 'area'],
    type: 'string',
  },
  {
    key: 'nivelCargo',
    label: 'Nivel Jerárquico',
    required: false,
    description: 'Directivo, Mando Medio, Profesional, Operativo, Asistencial',
    synonyms: ['nivel', 'jerarquia', 'clasificacioncargo', 'niveldelcargo'],
    type: 'string',
  },
  {
    key: 'jefeInmediato',
    label: 'Jefe Inmediato',
    required: false,
    description: 'Cargo a quien reporta directamente',
    synonyms: ['superiorsupervisor', 'reportaa', 'jefe', 'supervisor', 'jefeinmediato'],
    type: 'string',
  },
  {
    key: 'tipoContrato',
    label: 'Tipo de Contrato / Vinculación',
    required: false,
    description: 'Indefinido, Fijo, Obra o labor, Prestación de servicios',
    synonyms: ['contrato', 'modalidadcontrato', 'tipodecontratacion', 'tipodevinculacion', 'vinculacion'],
    type: 'string',
  },
  {
    key: 'jornada',
    label: 'Jornada Laboral',
    required: false,
    description: 'Tiempo completo, Turnos rotativos, Medio tiempo',
    synonyms: ['horario', 'turnos', 'jornada', 'jornadalaboral'],
    type: 'string',
  },
  {
    key: 'escalasSalarial',
    label: 'Rango / Escala Salarial',
    required: false,
    description: 'Rango de remuneración económica',
    synonyms: ['salario', 'sueldo', 'escalasalarial', 'remuneracion', 'escalasalarial'],
    type: 'string',
  },
  {
    key: 'numVacantes',
    label: 'Número de Personas en el Cargo',
    required: false,
    description: 'Cantidad de personas o vacantes asociadas',
    synonyms: ['vacantes', 'plazas', 'personas', 'cupos', 'cantidadtrabajadores', 'numerodevacantes', 'nodevacantes'],
    type: 'string',
  },
  {
    key: 'contextoAdicional',
    label: 'Misión / Descripción del Cargo',
    required: false,
    description: 'Propósito principal, funciones y contexto del puesto',
    synonyms: ['mision', 'objetivo', 'funciones', 'proposito', 'descripcion', 'descripciondetallada', 'contextoadicional'],
    type: 'string',
  },
  {
    key: 'eppSeleccionados',
    label: 'Elementos de Protección Personal (EPP)',
    required: false,
    description: 'Listado de EPP requeridos para el cargo',
    synonyms: ['epp', 'epprequeridos', 'elementosdeproteccionpersonal', 'proteccionpersonal', 'epps'],
    type: 'string',
  },
  {
    key: 'entrenamientosSeleccionados',
    label: 'Capacitaciones y Entrenamientos',
    required: false,
    description: 'Cursos obligatorios (alturas, espacios confinados, SST)',
    synonyms: ['entrenamientos', 'capacitaciones', 'cursos', 'formacion', 'entrenamientosrequeridos'],
    type: 'string',
  },
  {
    key: 'exigenciaFisica',
    label: 'Exigencia Física',
    required: false,
    description: 'Demanda física y biomecánica (cargas, posturas, bipedestación)',
    synonyms: ['exigenciafisica', 'demandafisica', 'esfuerzofisico'],
    type: 'string',
  },
  {
    key: 'exigenciaMental',
    label: 'Exigencia Mental / Psicosocial',
    required: false,
    description: 'Concentración, atención, toma de decisiones o estrés',
    synonyms: ['exigenciamental', 'demandamental', 'cargamental'],
    type: 'string',
  },
];

// ─── 4. Matriz IPEVR (GTC-45) ────────────────────────────────────────────────
export const MATRIZ_IPEVAR_FIELDS: TargetFieldDef[] = [
  {
    key: 'proceso',
    label: 'Proceso',
    required: true,
    description: 'Proceso estratégico, misional o de apoyo',
    synonyms: ['macroproceso', 'procesoempresa'],
    type: 'string',
  },
  {
    key: 'zona',
    label: 'Zona / Lugar',
    required: false,
    description: 'Área física o locación donde se realiza la actividad',
    synonyms: ['lugar', 'area', 'ubicacion', 'sitio', 'zonalugar'],
    type: 'string',
  },
  {
    key: 'actividad',
    label: 'Actividad',
    required: true,
    description: 'Nombre de la actividad evaluada',
    synonyms: ['nombreactividad', 'labor'],
    type: 'string',
  },
  {
    key: 'tareas',
    label: 'Tareas Específicas',
    required: false,
    description: 'Detalle de las tareas que componen la actividad',
    synonyms: ['tarea', 'tareasespecificas', 'pasos'],
    type: 'string',
  },
  {
    key: 'rutinaria',
    label: '¿Es Rutinaria? (Sí / No)',
    required: false,
    description: 'Frecuencia rutinaria de la labor',
    synonyms: ['rutina', 'esrutinaria', 'frecuente'],
    type: 'string',
  },
  {
    key: 'peligro_clasificacion',
    label: 'Clasificación del Peligro (GTC-45)',
    required: true,
    description: 'Biológico, Físico, Químico, Biomecánico, Psicosocial, Condiciones de seguridad, Fenómenos naturales',
    synonyms: ['clasificacion', 'tipopeligro', 'categoriapeligro', 'clasificacionpeligro'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Peligro',
    required: true,
    description: 'Fuente, situación o acto con potencial de daño',
    synonyms: ['peligro', 'factorriesgo', 'riesgo', 'descripcionpeligro', 'descripciondelpeligro'],
    type: 'string',
  },
  {
    key: 'efectos_posibles',
    label: 'Efectos Posibles en la Salud',
    required: false,
    description: 'Lesiones, enfermedades o consecuencias para los trabajadores',
    synonyms: ['efectos', 'consecuencias', 'danos', 'efectossalud', 'efectosposibles'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Rol Expuesto',
    required: false,
    description: 'Puesto de trabajo expuesto a este riesgo',
    synonyms: ['puestoexpuesto', 'cargos', 'ocupacion', 'cargo'],
    type: 'string',
  },
  {
    key: 'controles_fuente',
    label: 'Controles en la Fuente',
    required: false,
    description: 'Controles existentes en el origen del peligro',
    synonyms: ['fuente', 'controlfuente', 'controlesfuente'],
    type: 'string',
  },
  {
    key: 'controles_medio',
    label: 'Controles en el Medio',
    required: false,
    description: 'Controles existentes en la transmisión o ambiente',
    synonyms: ['medio', 'controlmedio', 'controlesmedio'],
    type: 'string',
  },
  {
    key: 'controles_individuo',
    label: 'Controles en el Individuo / EPP',
    required: false,
    description: 'Controles en el trabajador (capacitación, EPP, procedimientos)',
    synonyms: ['individuo', 'trabajador', 'epp', 'controlindividuo', 'controlesindividuo'],
    type: 'string',
  },
  {
    key: 'nd',
    label: 'Nivel de Deficiencia (ND)',
    required: false,
    description: 'Valores GTC-45: 10, 6, 2 o 0',
    synonyms: ['deficiencia', 'valordeficiencia', 'nd'],
    type: 'number',
  },
  {
    key: 'ne',
    label: 'Nivel de Exposición (NE)',
    required: false,
    description: 'Valores GTC-45: 4, 3, 2 o 1',
    synonyms: ['exposicion', 'valorexposicion', 'ne'],
    type: 'number',
  },
  {
    key: 'nc',
    label: 'Nivel de Consecuencia (NC)',
    required: false,
    description: 'Valores GTC-45: 100, 60, 25 o 10',
    synonyms: ['consecuencia', 'valorconsecuencia', 'nc'],
    type: 'number',
  },
  {
    key: 'medida_eliminacion',
    label: 'Medida de Eliminación',
    required: false,
    description: 'Medida propuesta para eliminar el peligro',
    synonyms: ['eliminacion', 'medidaeliminacion'],
    type: 'string',
  },
  {
    key: 'medida_sustitucion',
    label: 'Medida de Sustitución',
    required: false,
    description: 'Medida propuesta para sustituir el peligro',
    synonyms: ['sustitucion', 'medidasustitucion'],
    type: 'string',
  },
  {
    key: 'medida_ingenieria',
    label: 'Controles de Ingeniería',
    required: false,
    description: 'Medidas técnicas o de ingeniería propuestas',
    synonyms: ['ingenieria', 'controlingenieria', 'medidaingenieria'],
    type: 'string',
  },
  {
    key: 'medida_administrativa',
    label: 'Controles Administrativos',
    required: false,
    description: 'Procedimientos, señalización o capacitaciones propuestas',
    synonyms: ['administrativo', 'controladministrativo', 'medidaadministrativa', 'senializacion'],
    type: 'string',
  },
  {
    key: 'medida_eppu',
    label: 'Medida de EPP / Equipos de Protección',
    required: false,
    description: 'Equipos de protección personal propuestos',
    synonyms: ['epppropuesto', 'medidaepp', 'medidaeppu'],
    type: 'string',
  },
  {
    key: 'nro_expuestos',
    label: 'Número de Expuestos',
    required: false,
    description: 'Cantidad de personas expuestas al peligro',
    synonyms: ['expuestos', 'numeroexpuestos', 'nroexpuestos', 'cantidadexpuestos'],
    type: 'number',
  },
  {
    key: 'peor_consecuencia',
    label: 'Peor Consecuencia',
    required: false,
    description: 'Mayor daño previsible que puede ocasionar el peligro',
    synonyms: ['peorconsecuencia', 'consecuenciamayor'],
    type: 'string',
  },
  {
    key: 'requisito_legal',
    label: 'Requisito Legal Específico',
    required: false,
    description: 'Norma colombiana o técnica aplicable (ej. Res. 0312, Res. 2400)',
    synonyms: ['requisitolegal', 'normatividad', 'legal'],
    type: 'string',
  },
];

// ─── 5. Matriz PESV (Seguridad Vial) ─────────────────────────────────────────
export const MATRIZ_PESV_FIELDS: TargetFieldDef[] = [
  {
    key: 'cargo',
    label: 'Cargo del Colaborador',
    required: true,
    description: 'Cargo que realiza desplazamientos viales',
    synonyms: ['puesto', 'conductor', 'trabajador', 'cargotrabajador'],
    type: 'string',
  },
  {
    key: 'rol_via',
    label: 'Rol en la Vía (Actor Vial)',
    required: true,
    description: 'Conductor vehículo pesado, liviano, moto, bicicleta, peatón',
    synonyms: ['actorvial', 'rolvia', 'rol', 'tipoconductor'],
    type: 'string',
  },
  {
    key: 'tipo_desplazamiento',
    label: 'Tipo de Desplazamiento',
    required: false,
    description: 'Misional (durante la jornada) o In Itinere (casa-trabajo-casa)',
    synonyms: ['desplazamiento', 'tipoviaje', 'misionalinitinere'],
    type: 'string',
  },
  {
    key: 'factor_riesgo',
    label: 'Factor de Riesgo Vial',
    required: true,
    description: 'Factor Humano, Factor Vehicular, Factor Infraestructura o Entorno',
    synonyms: ['factor', 'clasificacionriesgovial', 'tipofactor'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Riesgo Vial',
    required: true,
    description: 'Exceso de velocidad, microsueño, estado de la vía, etc.',
    synonyms: ['peligro', 'riesgovial', 'situacionvial'],
    type: 'string',
  },
  {
    key: 'responsable',
    label: 'Responsable del Control',
    required: false,
    description: 'Cargo o persona encargada de la intervención',
    synonyms: ['responsablecontrol', 'lider'],
    type: 'string',
  },
];

// ─── 6. Matriz de Compatibilidad Química ─────────────────────────────────────
export const MATRIZ_COMPATIBILIDAD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre_comercial',
    label: 'Nombre Comercial / Producto Químico',
    required: true,
    description: 'Nombre del producto químico o sustancia almacenada',
    synonyms: ['producto', 'sustancia', 'quimico', 'reactivo', 'nombre'],
    type: 'string',
  },
  {
    key: 'numero_un',
    label: 'Número ONU (UN)',
    required: false,
    description: 'Código de 4 dígitos de Naciones Unidas (ej. UN 1203)',
    synonyms: ['un', 'onu', 'numeroun', 'codigoun', 'identificadoronu'],
    type: 'string',
  },
  {
    key: 'clase_peligro',
    label: 'Clase de Peligro Principal (SGA / ONU)',
    required: true,
    description: 'Clase de 1 a 9 (ej. Líquidos inflamables, Corrosivos, etc.)',
    synonyms: ['clase', 'categoria', 'clasificacionpeligro', 'claseonu'],
    type: 'string',
  },
  {
    key: 'estado_fisico',
    label: 'Estado Físico',
    required: false,
    description: 'Líquido, Sólido o Gas',
    synonyms: ['estado', 'formafisica'],
    type: 'string',
  },
  {
    key: 'area_almacenamiento',
    label: 'Área / Bodega de Almacenamiento',
    required: false,
    description: 'Ubicación física en la planta o bodega',
    synonyms: ['bodega', 'almacen', 'estante', 'ubicacion'],
    type: 'string',
  },
];

// ─── 7. Matriz Legal SG-SST ──────────────────────────────────────────────────
export const MATRIZ_LEGAL_FIELDS: TargetFieldDef[] = [
  {
    key: 'norma',
    label: 'Norma / Ley / Decreto / Resolución',
    required: true,
    description: 'Denominación de la norma (ej. Resolución 0312 de 2019, Decreto 1072 de 2015, Ley 9 de 1979)',
    synonyms: ['norma', 'ley', 'decreto', 'resolucion', 'normativa', 'normatividad', 'codigonorma', 'disposicion'],
    type: 'string',
  },
  {
    key: 'articulo',
    label: 'Artículo / Numeral / Estándar',
    required: false,
    description: 'Artículo, parágrafo o estándar aplicable (ej. E1.1.1, Art. 2.2.4.6.15)',
    synonyms: ['articulo', 'art', 'numeral', 'paragrafo', 'estandar', 'seccion', 'numeralestandar'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción / Requerimiento Legal',
    required: true,
    description: 'Texto u obligación legal exigida por la norma',
    synonyms: ['descripcion', 'requerimiento', 'exigencia', 'descripcionnorma', 'obligacion', 'requisito', 'textoarticulo'],
    type: 'string',
  },
  {
    key: 'evidencia',
    label: 'Evidencia de Cumplimiento / Mecanismo',
    required: false,
    description: 'Documento, registro o mecanismo que demuestra la conformidad',
    synonyms: ['evidencia', 'mecanismocumplimiento', 'soporte', 'formacumplimiento', 'documentoevidencia', 'verificacion'],
    type: 'string',
  },
  {
    key: 'categoria',
    label: 'Categoría / Eje Temático',
    required: false,
    description: 'Clasificación o estándar general (ej. Recursos, Peligros, COPASST, Emergencias)',
    synonyms: ['categoria', 'tema', 'ejetematico', 'capitulo', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado de Cumplimiento',
    required: false,
    description: 'Cumple, No Cumple o No Aplica',
    synonyms: ['estado', 'estadocumplimiento', 'cumplimiento', 'calificacion', 'conformidad', 'cumple'],
    type: 'string',
  },
  {
    key: 'seguimiento',
    label: 'Notas de Seguimiento / Responsable',
    required: false,
    description: 'Plan de acción, responsable o justificación',
    synonyms: ['seguimiento', 'observaciones', 'responsable', 'notas', 'justificacion', 'plandeaccion'],
    type: 'string',
  },
];

// ─── 8. Entrega y Seguimiento de EPP ─────────────────────────────────────────
export const EPP_TRACKING_FIELDS: TargetFieldDef[] = [
  {
    key: 'identificacion',
    label: 'Identificación / Cédula del Trabajador',
    required: true,
    description: 'Cédula o documento de quien recibe el EPP',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'dni', 'nodeidentificacion'],
    type: 'string',
  },
  {
    key: 'nombreTrabajador',
    label: 'Nombre del Trabajador',
    required: true,
    description: 'Nombre y apellidos del colaborador asignado',
    synonyms: ['nombre', 'trabajador', 'colaborador', 'empleado', 'nombretrabajador', 'nombresyapellidos', 'nombres'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo del Trabajador',
    required: false,
    description: 'Puesto o cargo desempeñado',
    synonyms: ['cargo', 'puesto', 'ocupacion', 'oficio'],
    type: 'string',
  },
  {
    key: 'elemento',
    label: 'Nombre del Elemento / EPP',
    required: true,
    description: 'Casco dieléctrico, Guantes nitrilo, Botas de seguridad, Monogafas, etc.',
    synonyms: ['elemento', 'epp', 'nombreepp', 'elementodeproteccion', 'proteccion', 'producto', 'articulo', 'descripcion'],
    type: 'string',
  },
  {
    key: 'tipo',
    label: 'Tipo de EPP (Regular / Alturas)',
    required: false,
    description: 'Clasificación entre Regular y Alturas',
    synonyms: ['tipo', 'tipoepp', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'marca',
    label: 'Marca / Fabricante',
    required: false,
    description: 'Marca del fabricante del elemento',
    synonyms: ['marca', 'fabricante', 'marcaepp'],
    type: 'string',
  },
  {
    key: 'referencia',
    label: 'Referencia / Modelo',
    required: false,
    description: 'Modelo o referencia del elemento',
    synonyms: ['referencia', 'modelo', 'ref'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Lote / Código',
    required: false,
    description: 'Código de trazabilidad o número de serie',
    synonyms: ['serial', 'lote', 'codigo', 'cod', 'numeroserie'],
    type: 'string',
  },
  {
    key: 'cantidad',
    label: 'Cantidad Entregada',
    required: false,
    description: 'Número de unidades dotadas',
    synonyms: ['cantidad', 'cant', 'unidades', 'dotacion'],
    type: 'number',
  },
  {
    key: 'fechaEntrega',
    label: 'Fecha de Entrega',
    required: true,
    description: 'Fecha en que se suministró el elemento',
    synonyms: ['fechaentrega', 'fecha', 'fentrega', 'fechasuministro', 'dotadofecha'],
    type: 'date',
  },
  {
    key: 'fechaVencimiento',
    label: 'Fecha de Vencimiento / Reposición',
    required: false,
    description: 'Fecha límite de vida útil o reposición periódica',
    synonyms: ['fechavencimiento', 'fvencimiento', 'vencimiento', 'proximareposicion', 'cambiofechafutura'],
    type: 'date',
  },
  {
    key: 'estado',
    label: 'Estado del EPP',
    required: false,
    description: 'Entregado, Vigente, Inspección Requerida, Fuera de Servicio',
    synonyms: ['estado', 'situacion', 'condicion', 'estadofisico'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Motivo de Entrega',
    required: false,
    description: 'Dotación periódica, reposición por daño, pérdida, etc.',
    synonyms: ['observaciones', 'motivo', 'notas', 'comentarios', 'detalle'],
    type: 'string',
  },
];

// ─── 9. Hoja de Vida Equipos en Alturas (Res. 4272/2021) ──────────────────────
export const EQUIPOS_ALTURAS_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Equipo de Alturas',
    required: true,
    description: 'Arnés de cuerpo entero, Eslinga con absorbedor, Línea de vida, Mosquetón, Casco con barbuquejo, etc.',
    synonyms: ['equipo', 'nombre', 'nombreequipo', 'tipoequipo', 'elemento', 'descripcion'],
    type: 'string',
  },
  {
    key: 'marca',
    label: 'Marca / Fabricante',
    required: false,
    description: 'Marca fabricante (ej. MSA, 3M DBI-SALA, Petzl, SOSEGA, Armadura)',
    synonyms: ['marca', 'fabricante', 'brand'],
    type: 'string',
  },
  {
    key: 'referencia',
    label: 'Referencia / Modelo',
    required: false,
    description: 'Modelo de fábrica o código de referencia',
    synonyms: ['referencia', 'modelo', 'ref', 'model'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Lote / Código Único',
    required: true,
    description: 'Número de serie único de trazabilidad para inspección obligatoria',
    synonyms: ['serial', 'lote', 'codigo', 'numeroserie', 'serienumero', 'id', 'placa'],
    type: 'string',
  },
  {
    key: 'fechaFabricacion',
    label: 'Fecha de Fabricación',
    required: false,
    description: 'Fecha de elaboración según etiqueta técnica',
    synonyms: ['fechafabricacion', 'fabricacion', 'ffabricacion', 'anofabricacion'],
    type: 'date',
  },
  {
    key: 'fechaCompra',
    label: 'Fecha de Compra / Puesta en Servicio',
    required: false,
    description: 'Fecha en que entró en servicio en la empresa',
    synonyms: ['fechacompra', 'puestaservicio', 'fechapuestaservicio', 'ingreso', 'fechaingreso'],
    type: 'date',
  },
  {
    key: 'fechaUltimaInspeccion',
    label: 'Fecha de Última Inspección',
    required: false,
    description: 'Fecha de la inspección por persona calificada',
    synonyms: ['fechaultimainspeccion', 'ultimainspeccion', 'fechainspeccion', 'finspeccion'],
    type: 'date',
  },
  {
    key: 'fechaProximaInspeccion',
    label: 'Fecha de Próxima Inspección',
    required: false,
    description: 'Próxima revisión obligatoria (máximo anual)',
    synonyms: ['fechaproximainspeccion', 'proximainspeccion', 'fechasiguienterevision', 'vencimientoinspeccion'],
    type: 'date',
  },
  {
    key: 'inspeccionadoPor',
    label: 'Inspector / Persona Calificada',
    required: false,
    description: 'Nombre de la persona calificada que realizó la inspección',
    synonyms: ['inspeccionadopor', 'inspector', 'personacalificada', 'responsableinspeccion'],
    type: 'string',
  },
  {
    key: 'resultadoInspeccion',
    label: 'Resultado Inspección (Aprobado / Rechazado)',
    required: false,
    description: 'Aprobado, Rechazado o N/A',
    synonyms: ['resultadoinspeccion', 'resultado', 'concepto', 'dictamen'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado Operativo del Equipo',
    required: false,
    description: 'Vigente, Vencido, Requiere Inspección, Retirado',
    synonyms: ['estado', 'condicion', 'situacion', 'operatividad'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Criterios de Descarte',
    required: false,
    description: 'Desgaste en costuras, corrosión metálica, deformación o notas',
    synonyms: ['observaciones', 'notas', 'detalles', 'criteriosdescarte', 'comentarios'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Cédula del Trabajador Asignado',
    required: false,
    description: 'Cédula del colaborador custodio del equipo',
    synonyms: ['cedula', 'cc', 'documento', 'identificaciontrabajador'],
    type: 'string',
  },
  {
    key: 'nombreTrabajador',
    label: 'Nombre del Trabajador Asignado',
    required: false,
    description: 'Nombre del colaborador al que se le entregó el equipo',
    synonyms: ['trabajador', 'colaborador', 'asignadoa', 'custodio', 'nombretrabajador'],
    type: 'string',
  },
];

// ─── 10. Inventario e Inspección de Equipos de Emergencia ─────────────────────
export const EQUIPOS_EMERGENCIA_FIELDS: TargetFieldDef[] = [
  {
    key: 'categoria',
    label: 'Tipo de Equipo / Recurso de Emergencia',
    required: true,
    description: 'Extintor Multipropósito ABC, Extintor Solkaflam, Extintor CO2, Botiquín Tipo A/B/C, Camilla Rígida, Lámpara de Emergencia, Alarma, etc.',
    synonyms: ['equipo', 'categoria', 'tipoequipo', 'recurso', 'descripcion', 'claseequipo', 'nombre'],
    type: 'string',
  },
  {
    key: 'capacidad',
    label: 'Capacidad / Especificación Técnica',
    required: false,
    description: '10 lbs, 20 lbs, 3700 gr, Dotación NTC 4198, 180 kg, 2 horas de autonomía, etc.',
    synonyms: ['capacidad', 'especificacion', 'peso', 'tamano', 'medida', 'especificaciontecnica'],
    type: 'string',
  },
  {
    key: 'ubicacion',
    label: 'Ubicación Física / Área / Piso',
    required: true,
    description: 'Pasillo Principal, Recepción, Bodega de Químicos, Piso 2, Entrada Portería, etc.',
    synonyms: ['ubicacion', 'area', 'piso', 'lugar', 'sitio', 'sector', 'ubicacionfisica'],
    type: 'string',
  },
  {
    key: 'vencimiento',
    label: 'Fecha de Vencimiento / Próxima Recarga',
    required: true,
    description: 'Fecha límite de vigencia de la carga o de los insumos del botiquín',
    synonyms: ['vencimiento', 'fechavencimiento', 'proximarecarga', 'recarga', 'fecharecarga', 'fvencimiento'],
    type: 'date',
  },
  {
    key: 'estado',
    label: 'Estado Operativo del Recurso',
    required: false,
    description: 'Operativo, Recarga Pendiente, En Mantenimiento, Fuera de Servicio, Incompleto',
    synonyms: ['estado', 'condicion', 'situacion', 'operatividad', 'estadorecurso'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Número de Placa / Identificador',
    required: false,
    description: 'Código de identificación física del extintor o botiquín',
    synonyms: ['serial', 'placa', 'id', 'numeroextintor', 'codigo', 'identificador'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Novedades de Inspección',
    required: false,
    description: 'Presión de manómetro, precinto de seguridad, señalización, soporte o notas',
    synonyms: ['observaciones', 'novedades', 'notas', 'inspeccion', 'comentarios'],
    type: 'string',
  },
];

// ─── 11. Programa de Capacitación en SG-SST ──────────────────────────────────
export const PROGRAMA_CAPACITACION_FIELDS: TargetFieldDef[] = [
  {
    key: 'tema',
    label: 'Tema de Capacitación',
    required: true,
    description: 'Inducción SG-SST, Manejo de Extintores, Trabajo Seguro en Alturas, Riesgo Biomecánico, Primeros Auxilios, etc.',
    synonyms: ['tema', 'capacitacion', 'nombrecapacitacion', 'actividad', 'curso', 'modulo', 'titulocapacitacion'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción / Objetivo / Alcance',
    required: false,
    description: 'Objetivo de aprendizaje o contenido de la sesión',
    synonyms: ['descripcion', 'objetivo', 'alcance', 'temario', 'detalles', 'contenido'],
    type: 'string',
  },
  {
    key: 'fecha',
    label: 'Fecha Programada',
    required: true,
    description: 'Fecha de ejecución o planeación (YYYY-MM-DD)',
    synonyms: ['fecha', 'fechaprogramada', 'fechasesion', 'diacapacitacion', 'fechaplaneada'],
    type: 'date',
  },
  {
    key: 'hora',
    label: 'Hora de Inicio',
    required: false,
    description: 'Hora de inicio de la sesión (ej. 08:00 AM, 14:00)',
    synonyms: ['hora', 'horainicio', 'horario'],
    type: 'string',
  },
  {
    key: 'duracion',
    label: 'Duración (Horas)',
    required: false,
    description: 'Intensidad horaria (ej. 1 hora, 2 horas, 4 horas)',
    synonyms: ['duracion', 'intensidad', 'horas', 'duracionhoras', 'intensidadhoraria'],
    type: 'string',
  },
  {
    key: 'responsable',
    label: 'Responsable / Facilitador / Entidad',
    required: false,
    description: 'ARL, Profesional SST, Bomberos, Entrenador SENA, etc.',
    synonyms: ['responsable', 'facilitador', 'capacitador', 'entidad', 'instructor', 'docente'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado de la Capacitación',
    required: false,
    description: 'Programada, Ejecutada / Completada, Cancelada, Reprogramada',
    synonyms: ['estado', 'situacion', 'condicion', 'cumplimiento'],
    type: 'string',
  },
  {
    key: 'publicoObjetivo',
    label: 'Público Objetivo / Población Convocada',
    required: false,
    description: 'Todo el personal, Personal operativo, Brigadistas, Miembros COPASST, etc.',
    synonyms: ['publico', 'poblacion', 'cargos', 'asistentes', 'destinatarios', 'publicoobjetivo'],
    type: 'string',
  },
];

// ─── 12. Gestión Integral de Ausentismo y ATEL ────────────────────────────────
export const AUSENTISMO_FIELDS: TargetFieldDef[] = [
  {
    key: 'fecha',
    label: 'Fecha de Inicio de Incapacidad / Ausencia',
    required: true,
    description: 'Fecha desde la cual inicia el periodo de ausencia (YYYY-MM-DD)',
    synonyms: ['fechainicio', 'fecha', 'fechadesde', 'desde', 'iniciodescanso', 'fechaincapacidad'],
    type: 'date',
  },
  {
    key: 'fechaFin',
    label: 'Fecha de Fin de Incapacidad',
    required: false,
    description: 'Fecha final del descanso médico o permiso',
    synonyms: ['fechafin', 'fechahasta', 'hasta', 'findescanso', 'fechareintegro'],
    type: 'date',
  },
  {
    key: 'tipo',
    label: 'Tipo de Evento / Causa de Ausentismo',
    required: true,
    description: 'AT (Accidente Trabajo), EL (Enfermedad Laboral), EG_EPS (Enfermedad General), ACC_COMUN, LIC_MAT, LIC_PAT, LUTO, etc.',
    synonyms: ['tipo', 'tipoevento', 'causa', 'motivo', 'clasificacion', 'tiponovedad', 'origenincapacidad'],
    type: 'string',
  },
  {
    key: 'diasIncapacidad',
    label: 'Días de Incapacidad / Días Ausentes',
    required: true,
    description: 'Cantidad de días otorgados en la certificación médica',
    synonyms: ['dias', 'diasincapacidad', 'diasotorgados', 'diasausencia', 'cantidaddias', 'nrodias'],
    type: 'number',
  },
  {
    key: 'horasAusencia',
    label: 'Horas de Ausencia (si aplica)',
    required: false,
    description: 'Horas laborales perdidas para permisos o citas médicas',
    synonyms: ['horas', 'horasausencia', 'horasperdidas'],
    type: 'number',
  },
  {
    key: 'cie10',
    label: 'Código CIE-10 / Diagnóstico',
    required: false,
    description: 'Código alfanumérico CIE-10 (ej. M545 Lumbago, S934 Esguince de tobillo, J069)',
    synonyms: ['cie10', 'diagnostico', 'codigocie10', 'patologia', 'diagnosticoeps', 'cie'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción del Evento / Consecuencia',
    required: false,
    description: 'Detalle de la lesión, síntoma o motivo de la ausencia',
    synonyms: ['descripcion', 'detalle', 'consecuencia', 'observacion', 'diagnosticoescrito'],
    type: 'string',
  },
  {
    key: 'nombre',
    label: 'Nombre del Colaborador',
    required: true,
    description: 'Nombre completo del trabajador ausente',
    synonyms: ['nombre', 'trabajador', 'colaborador', 'empleado', 'nombresyapellidos', 'nombres'],
    type: 'string',
  },
  {
    key: 'cedula',
    label: 'Cédula / Documento de Identidad',
    required: false,
    description: 'Número de documento de identidad del trabajador',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'dni'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Puesto del Colaborador',
    required: false,
    description: 'Cargo desempeñado en la empresa',
    synonyms: ['cargo', 'puesto', 'ocupacion', 'oficio'],
    type: 'string',
  },
  {
    key: 'salario',
    label: 'Salario Base / IBC Mensual',
    required: false,
    description: 'Ingreso Base de Cotización para costeo financiero de ausentismo',
    synonyms: ['salario', 'sueldo', 'ibc', 'remuneracion', 'ibcmensual', 'salariobase'],
    type: 'number',
  },
  {
    key: 'entidad',
    label: 'Entidad de Salud (EPS / ARL)',
    required: false,
    description: 'Nombre de la EPS o ARL que emitió o cubre la incapacidad',
    synonyms: ['entidad', 'eps', 'arl', 'entidadsalud', 'aseguradora'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Estado de Recobro',
    required: false,
    description: 'En trámite de cobro, reconocido, pagado, observaciones generales',
    synonyms: ['observaciones', 'recobro', 'notas', 'comentarios', 'tramiterecobro'],
    type: 'string',
  },
];

// ─── 13. Tablero Kanban ACPM (Acciones Correctivas, Preventivas y Mejora) ─────
export const KANBAN_ACPM_FIELDS: TargetFieldDef[] = [
  {
    key: 'title',
    label: 'Título de la Acción / Tarea ACPM',
    required: true,
    description: 'Nombre de la acción correctiva, preventiva, de mejora o compromiso',
    synonyms: ['actividad', 'tarea', 'titulo', 'nombre', 'accion', 'plandeaccion', 'compromiso', 'activity', 'title', 'nombretarea'],
    type: 'string',
  },
  {
    key: 'description',
    label: 'Descripción / Hallazgo / Causa Raíz',
    required: false,
    description: 'No conformidad identificada, causa raíz analizada o alcance del control',
    synonyms: ['descripcion', 'hallazgo', 'causaraiz', 'noconformidad', 'detalles', 'detalle', 'description', 'alcance'],
    type: 'string',
  },
  {
    key: 'dueDate',
    label: 'Fecha Límite / Fecha de Cierre',
    required: true,
    description: 'Fecha máxima para implementar y cerrar la acción (YYYY-MM-DD)',
    synonyms: ['fechalimite', 'fecha', 'vencimiento', 'fechacierre', 'duedate', 'fechaentrega', 'plazo', 'fechaprogramada'],
    type: 'date',
  },
  {
    key: 'status',
    label: 'Estado de la Tarea (todo / due_soon / overdue / done)',
    required: false,
    description: 'Por hacer (todo), Próxima a vencer (due_soon), Vencida (overdue) o Completada (done)',
    synonyms: ['estado', 'status', 'columna', 'situacion', 'fase'],
    type: 'string',
  },
  {
    key: 'actionType',
    label: 'Tipo de Acción ACPM (Correctiva / Preventiva / Mejora)',
    required: false,
    description: 'Clasificación de la acción según PHVA',
    synonyms: ['tipoaccion', 'acciontipo', 'acpm', 'tipoacpm', 'clasificacionaccion'],
    type: 'string',
  },
  {
    key: 'priority',
    label: 'Prioridad (Alta / Media / Baja)',
    required: false,
    description: 'Nivel de urgencia o criticidad del hallazgo',
    synonyms: ['prioridad', 'criticidad', 'urgencia', 'priority', 'severidad'],
    type: 'string',
  },
  {
    key: 'assignedTo',
    label: 'Responsable Asignado',
    required: false,
    description: 'Persona o cargo responsable de implementar y cerrar la tarea',
    synonyms: ['responsable', 'asignadoa', 'encargado', 'lider', 'assignedto', 'ejecutor'],
    type: 'string',
  },
  {
    key: 'sourceModule',
    label: 'Módulo de Origen / Fuente del Hallazgo',
    required: false,
    description: 'Auditoría, Inspección, COPASST, IPEVR, ATEL, PESV, etc.',
    synonyms: ['origen', 'fuente', 'sourcemodule', 'moduloorigen', 'procedencia'],
    type: 'string',
  },
];

// ─── 14. Análisis de Vulnerabilidad y Emergencias ─────────────────────────────
export const VULNERABILIDAD_FIELDS: TargetFieldDef[] = [
  {
    key: 'amenaza',
    label: 'Nombre de la Amenaza',
    required: true,
    description: 'Sismo, Inundación, Incendio, Fuga de gas, Derrame de químicos, Robo / Asalto, etc.',
    synonyms: ['amenaza', 'peligro', 'nombreamenaza', 'evento', 'eventoamenazante', 'riesgo'],
    type: 'string',
  },
  {
    key: 'origenAmenaza',
    label: 'Origen de la Amenaza (Natural / Tecnológico / Social)',
    required: false,
    description: 'Natural (Sismo, Inundación...), Tecnológico (Incendio, Derrame...) o Social (Robo, Atentado...)',
    synonyms: ['origen', 'origenamenaza', 'tipoamenaza', 'fuente', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'nivelAmenaza',
    label: 'Calificación de la Amenaza (Posible / Probable / Inminente)',
    required: false,
    description: 'Nivel estimado de probabilidad o recurrencia',
    synonyms: ['nivel', 'nivelamenaza', 'calificacion', 'probabilidad', 'frecuencia'],
    type: 'string',
  },
  {
    key: 'descripcionGlobal',
    label: 'Descripción / Antecedentes de la Amenaza',
    required: false,
    description: 'Historial en la empresa, cercanías a fallas geológicas, ríos o zonas industriales',
    synonyms: ['descripcion', 'antecedentes', 'descripcionglobal', 'historial', 'observaciones'],
    type: 'string',
  },
  {
    key: 'medidasExistentes',
    label: 'Medidas de Prevención Existentes',
    required: false,
    description: 'Controles actuales (detectores de humo, brigada, rutas de evacuación, etc.)',
    synonyms: ['medidasexistentes', 'controles', 'medidasactuales', 'prevencion', 'controlesexistentes'],
    type: 'string',
  },
];

