/**
 * moduleFieldDefinitions.ts — Definiciones de campos oficiales para los aplicativos de WAPPY
 * Usado por el Mapeador Universal de Columnas (Paralelo de Casillas).
 */

import { TargetFieldDef } from './columnMapperEngine';

// ─── 1. Perfil Sociodemográfico ──────────────────────────────────────────────
export const SOCIODEMOGRAFICO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre Completo',
    required: true,
    description: 'Nombres y apellidos completos del trabajador',
    synonyms: ['nombres', 'apellidos', 'nombrecompleto', 'colaborador', 'empleado', 'trabajador', 'nombresyapellidos', 'apellidosynombres'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Número de Identificación / Cédula',
    required: true,
    description: 'Cédula de ciudadanía, extranjería, PEP o PPT',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'numerocedula', 'dni', 'nodeidentificacion', 'nodedocumento', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Puesto de Trabajo',
    required: false,
    description: 'Cargo actual desempeñado en la empresa',
    synonyms: ['puesto', 'ocupacion', 'oficio', 'cargotrabajador', 'puestotrabajo', 'cargoactual'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino, Femenino u Otro',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaNacimiento',
    label: 'Fecha de Nacimiento',
    required: false,
    description: 'Formato YYYY-MM-DD o DD/MM/AAAA',
    synonyms: ['fnacimiento', 'fechanac', 'fechanacimiento', 'cumpleanos', 'natalicio'],
    type: 'date',
  },
  {
    key: 'estadoCivil',
    label: 'Estado Civil',
    required: false,
    description: 'Soltero, Casado, Unión libre, Separado, Viudo',
    synonyms: ['estadocivil', 'estadocivilactual'],
    type: 'string',
  },
  {
    key: 'nivelEscolaridad',
    label: 'Nivel de Escolaridad',
    required: false,
    description: 'Primaria, Bachiller, Técnico, Tecnólogo, Profesional, Posgrado',
    synonyms: ['escolaridad', 'estudios', 'gradoinstruccion', 'nivelacademico', 'titulacion'],
    type: 'string',
  },
  {
    key: 'telefono',
    label: 'Teléfono / Celular',
    required: false,
    description: 'Número de contacto móvil o fijo',
    synonyms: ['celular', 'tel', 'movil', 'telefonofijo', 'numerocelular', 'contacto'],
    type: 'string',
  },
  {
    key: 'correoElectronico',
    label: 'Correo Electrónico',
    required: false,
    description: 'Email corporativo o personal',
    synonyms: ['email', 'correo', 'mail', 'correopersonal', 'correocorporativo'],
    type: 'string',
  },
  {
    key: 'direccion',
    label: 'Dirección de Residencia',
    required: false,
    description: 'Dirección física de domicilio',
    synonyms: ['domicilio', 'residencia', 'direcciondomicilio'],
    type: 'string',
  },
  {
    key: 'barrio',
    label: 'Barrio',
    required: false,
    description: 'Barrio de residencia',
    synonyms: ['sector', 'barrioresidencia'],
    type: 'string',
  },
  {
    key: 'municipioDomicilio',
    label: 'Municipio / Ciudad',
    required: false,
    description: 'Ciudad de residencia habitual',
    synonyms: ['ciudad', 'municipio', 'poblacion'],
    type: 'string',
  },
  {
    key: 'estrato',
    label: 'Estrato Socioeconómico',
    required: false,
    description: 'Estrato de 1 a 6',
    synonyms: ['estratosocioeconomico'],
    type: 'string',
  },
  {
    key: 'vivienda',
    label: 'Tipo de Vivienda',
    required: false,
    description: 'Propia, Arrendada, Familiar, etc.',
    synonyms: ['tipovivienda', 'tenenciavivienda'],
    type: 'string',
  },
  {
    key: 'personasCargo',
    label: 'Personas a Cargo / Hijos',
    required: false,
    description: 'Cantidad de personas dependientes',
    synonyms: ['hijos', 'personascargo', 'dependientes', 'numhijos', 'numerohijos'],
    type: 'number',
  },
  {
    key: 'salario',
    label: 'Salario / Remuneración',
    required: false,
    description: 'Salario base o rango salarial',
    synonyms: ['sueldo', 'remuneracion', 'salariobasico', 'ingresos'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma?',
    required: false,
    description: 'Hábito de tabaquismo (Sí / No)',
    synonyms: ['fumador', 'cigarrillo', 'tabaco', 'consumotabaco'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'deporte',
    label: 'Actividad Física / Deporte',
    required: false,
    description: 'Frecuencia o tipo de ejercicio físico',
    synonyms: ['actividadfisica', 'ejercicio', 'practicadeporte'],
    type: 'string',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnósticos Médicos Previos',
    required: false,
    description: 'Antecedentes o patologías diagnosticadas',
    synonyms: ['diagnostico', 'patologia', 'enfermedades', 'antecedentes'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha Último Examen Médico',
    required: false,
    description: 'Fecha de valoración médica ocupacional',
    synonyms: ['fechaexamen', 'fechamedico', 'ultimoexamen', 'examenocupacional'],
    type: 'date',
  },
  {
    key: 'recomendacionesMedicas',
    label: 'Recomendaciones y Restricciones Médicas',
    required: false,
    description: 'Concepto de aptitud, recomendaciones o restricciones laborales',
    synonyms: ['restricciones', 'recomendaciones', 'medidas', 'indicaciones', 'conceptomedico', 'aptitudmedica'],
    type: 'string',
  },
  {
    key: 'fechaSeguimiento',
    label: 'Fecha Próximo Seguimiento Médico',
    required: false,
    description: 'Fecha programada de control médico laboral',
    synonyms: ['proximocontrol', 'seguimiento', 'fechaseguimiento', 'fechavencimientoexamen'],
    type: 'date',
  },
  {
    key: 'lugarNacimiento',
    label: 'Lugar de Nacimiento',
    required: false,
    description: 'Ciudad y departamento de nacimiento',
    synonyms: ['lugarnacimiento', 'ciudadorigen', 'nacimiento'],
    type: 'string',
  },
  {
    key: 'emergenciaContacto',
    label: 'Contacto de Emergencia',
    required: false,
    description: 'Nombre y teléfono de contacto en caso de emergencia',
    synonyms: ['contactoemergencia', 'emergencia', 'avisara', 'familiarcontacto', 'emergenciacontacto'],
    type: 'string',
  },
  {
    key: 'tipoSangre',
    label: 'Tipo de Sangre / RH',
    required: false,
    description: 'Grupo sanguíneo y factor RH (ej. O+, A+, B-, etc.)',
    synonyms: ['rh', 'gruposanguineo', 'tiposangre', 'factorrh', 'sangre'],
    type: 'string',
  },
  {
    key: 'peso',
    label: 'Peso (Kg)',
    required: false,
    description: 'Peso corporal en kilogramos',
    synonyms: ['pesokg', 'pesocorporal', 'kg', 'peso'],
    type: 'string',
  },
  {
    key: 'talla',
    label: 'Talla / Estatura (m o cm)',
    required: false,
    description: 'Estatura en centímetros o metros',
    synonyms: ['estatura', 'altura', 'cm', 'tallacm', 'talla'],
    type: 'string',
  },
  {
    key: 'imc',
    label: 'Índice de Masa Corporal (IMC)',
    required: false,
    description: 'Valor numérico o clasificación IMC',
    synonyms: ['indicemasacorporal', 'masacorporal', 'imc'],
    type: 'string',
  },
  {
    key: 'presionArterial',
    label: 'Presión Arterial (Tensión)',
    required: false,
    description: 'Tensión arterial sistólica/diastólica',
    synonyms: ['tension', 'tensionarterial', 'ta', 'pa', 'presionarterial'],
    type: 'string',
  },
  {
    key: 'frecuenciaCardiaca',
    label: 'Frecuencia Cardíaca (lpm)',
    required: false,
    description: 'Pulsaciones por minuto en reposo',
    synonyms: ['pulso', 'fc', 'latidos', 'frecuenciacardiaca'],
    type: 'string',
  },
  {
    key: 'limitacionesBiomecanicas',
    label: 'Limitaciones Biomecánicas',
    required: false,
    description: 'Restricciones posturales, de levantamiento de cargas o movimientos repetitivos',
    synonyms: ['limitacion', 'biomecanica', 'ergonomia', 'restriccionbiomecanica', 'limitacionesbiomecanicas'],
    type: 'string',
  },
  {
    key: 'alergiasQuimicas',
    label: 'Alergias o Sustancias Químicas',
    required: false,
    description: 'Alergias a medicamentos, alimentos, látex o agentes químicos',
    synonyms: ['alergias', 'alergia', 'reacciones', 'alergiasquimicas'],
    type: 'string',
  },
  {
    key: 'enfermedades',
    label: 'Enfermedades Comunes / Antecedentes',
    required: false,
    description: 'Patologías crónicas (hipertensión, diabetes, asma, etc.)',
    synonyms: ['enfermedades', 'antecedentespatologicos', 'enfermedadesprevias', 'patologias'],
    type: 'string',
  },
  {
    key: 'medicamentos',
    label: 'Medicamentos Habituales',
    required: false,
    description: 'Tratamientos farmacológicos prescritos y uso continuo',
    synonyms: ['medicamentos', 'medicacion', 'farmacos', 'tratamiento'],
    type: 'string',
  },
  {
    key: 'alimentacion',
    label: 'Hábito de Alimentación',
    required: false,
    description: 'Dieta balanceada, consumo de agua o hábitos nutricionales',
    synonyms: ['alimentacion', 'nutricion', 'dieta', 'habitosalimenticios'],
    type: 'string',
  },
  {
    key: 'riesgoCardiovascular',
    label: 'Riesgo Cardiovascular (Framingham)',
    required: false,
    description: 'Clasificación de riesgo cardiovascular (Bajo, Medio, Alto)',
    synonyms: ['riesgocardiovascular', 'rcv', 'framingham', 'cardiovascular'],
    type: 'string',
  },
  {
    key: 'terapiaPsicologica',
    label: 'Terapia Psicológica / Apoyo Psicosocial',
    required: false,
    description: 'Antecedentes de acompañamiento o terapia psicológica (Sí/No)',
    synonyms: ['terapiapsicologica', 'psicologia', 'apoyopsicosocial', 'saludmental'],
    type: 'string',
  },
  {
    key: 'licenciaConduccion',
    label: 'Licencia de Conducción (Categorías)',
    required: false,
    description: 'Categorías de conducción (ej. A2, B1, C1, C2)',
    synonyms: ['licenciaconduccion', 'pase', 'licencia', 'categoriapase', 'licencias'],
    type: 'string',
  },
  {
    key: 'licenciaConduccionVencimiento',
    label: 'Vencimiento Licencia de Conducción',
    required: false,
    description: 'Fecha de expiración de la licencia de conducir',
    synonyms: ['vencimientolicencia', 'vencimientopase', 'licenciaconduccionvencimiento', 'fvencimientolicencia'],
    type: 'date',
  },
  {
    key: 'soatVencimiento',
    label: 'Vencimiento SOAT (Vehículo habitual)',
    required: false,
    description: 'Fecha de vencimiento del seguro obligatorio',
    synonyms: ['soatvencimiento', 'soat', 'vencimientosoat', 'fechasoat'],
    type: 'date',
  },
  {
    key: 'tecnicomecanicaVencimiento',
    label: 'Vencimiento Tecnomecánica',
    required: false,
    description: 'Fecha de vencimiento de la revisión tecnomecánica',
    synonyms: ['tecnicomecanica', 'tecnomecanica', 'tecnicomecanicavencimiento', 'vencimientotecnomecanica'],
    type: 'date',
  },
  {
    key: 'fechaCursoAlturasAutorizado',
    label: 'Fecha Curso Alturas Trabajador Autorizado',
    required: false,
    description: 'Fecha de certificación vigente para trabajo seguro en alturas (Res. 4272/2021)',
    synonyms: ['cursoalturas', 'fechacursoalturas', 'alturasautorizado', 'fechacursoalturasautorizado', 'alturas'],
    type: 'date',
  },
  {
    key: 'fechaCursoAlturasCoordinador',
    label: 'Fecha Curso Coordinador de Alturas',
    required: false,
    description: 'Certificación vigente de coordinador de trabajo seguro en alturas',
    synonyms: ['coordinadoralturas', 'fechacursoalturascoordinador', 'cursoalturascoordinador'],
    type: 'date',
  },
  {
    key: 'curso50h',
    label: 'Curso Virtual 50 Horas SG-SST',
    required: false,
    description: 'Certificación de 50 horas de SG-SST (Sí / No / Fecha)',
    synonyms: ['curso50h', 'curso50horas', 'curso50', '50horas', 'capacitacion50h'],
    type: 'string',
  },
  {
    key: 'curso20h',
    label: 'Actualización 20 Horas SG-SST',
    required: false,
    description: 'Certificación de actualización de 20 horas de SG-SST (Sí / No / Fecha)',
    synonyms: ['curso20h', 'curso20horas', 'curso20', '20horas', 'actualizacion20h'],
    type: 'string',
  },
  {
    key: 'licenciaSST',
    label: 'Licencia en Seguridad y Salud en el Trabajo',
    required: false,
    description: 'Número de resolución de licencia SST para profesionales/tecnólogos',
    synonyms: ['licenciasst', 'resolucionlicencia', 'nolicenciasst'],
    type: 'string',
  },
  {
    key: 'esCopasst',
    label: '¿Pertenece al COPASST / Vigía?',
    required: false,
    description: 'Miembro activo del Comité Paritario de SST (Sí / No)',
    synonyms: ['escopasst', 'copasst', 'vigiasst', 'miembrodelcopasst'],
    type: 'string',
  },
  {
    key: 'esComiteConvivencia',
    label: '¿Pertenece al Comité de Convivencia?',
    required: false,
    description: 'Miembro del Comité de Convivencia Laboral (Sí / No)',
    synonyms: ['escomiteconvivencia', 'comiteconvivencia', 'ccl', 'convivencialaboral'],
    type: 'string',
  },
  {
    key: 'esBrigadista',
    label: '¿Es Brigadista de Emergencias?',
    required: false,
    description: 'Miembro de la Brigada de Emergencia (Sí / No)',
    synonyms: ['esbrigadista', 'brigadista', 'brigadadeemergencias', 'brigadadeemergencia'],
    type: 'string',
  },
  {
    key: 'esComiteSeguridadVial',
    label: '¿Pertenece al Comité de Seguridad Vial (PESV)?',
    required: false,
    description: 'Miembro del Comité de Seguridad Vial (Sí / No)',
    synonyms: ['escomiteseguridadvial', 'comiteseguridadvial', 'comitepesv', 'pesvcomite'],
    type: 'string',
  },
  {
    key: 'estadoPila',
    label: 'Estado de Soporte PILA / Afiliación',
    required: false,
    description: 'Verificación de aportes a la seguridad social',
    synonyms: ['estadopila', 'pila', 'aportespila', 'seguridadsocial'],
    type: 'string',
  },
  {
    key: 'estadoLaboral',
    label: 'Estado Laboral (Activo / Retirado)',
    required: false,
    description: 'Situación laboral actual en la empresa',
    synonyms: ['estadolaboral', 'estado', 'condicionlaboral', 'activo', 'situacionlaboral'],
    type: 'string',
  },
  {
    key: 'fechaRetiro',
    label: 'Fecha de Retiro / Desvinculación',
    required: false,
    description: 'Fecha de retiro en caso de extrabajadores',
    synonyms: ['fecharetiro', 'retiro', 'fechadesvinculacion', 'desvinculacion'],
    type: 'date',
  },
  {
    key: 'motivoRetiro',
    label: 'Motivo de Retiro',
    required: false,
    description: 'Causa de retiro (Renuncia, Terminación de contrato, etc.)',
    synonyms: ['motivoretiro', 'causaretiro', 'razonretiro'],
    type: 'string',
  },
];

// ─── 2. Condiciones de Salud ────────────────────────────────────────────────
export const CONDICIONES_SALUD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Trabajador',
    required: true,
    description: 'Nombre y apellidos del colaborador',
    synonyms: ['trabajador', 'colaborador', 'empleado', 'nombresyapellidos', 'nombrecompleto', 'nombres', 'apellidos'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Identificación / Cédula',
    required: true,
    description: 'Número de documento de identidad',
    synonyms: ['cedula', 'cc', 'documento', 'numeroidentificacion', 'dni', 'nodeidentificacion', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo',
    required: false,
    description: 'Cargo u ocupación evaluada',
    synonyms: ['puesto', 'oficio', 'cargotrabajador', 'puestotrabajo'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino o Femenino',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha del Examen Médico',
    required: false,
    description: 'Fecha en que se practicó la evaluación ocupacional',
    synonyms: ['fecha', 'fechavaloracion', 'fechamedica', 'fechaexamen', 'fechadelexamen', 'ultimoexamen'],
    type: 'date',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnóstico Médico (CIE-10)',
    required: false,
    description: 'Código CIE-10 o descripción médica del diagnóstico',
    synonyms: ['diagnostico', 'cie10', 'patologia', 'hallazgo', 'enfermedad', 'diagnosticoprincipal', 'conceptomedico'],
    type: 'string',
  },
  {
    key: 'recomendacionesMedicas',
    label: 'Recomendaciones y Restricciones',
    required: false,
    description: 'Medidas médico-laborales preventivas, restricciones o correctivas',
    synonyms: ['restricciones', 'recomendaciones', 'medidas', 'indicaciones', 'restriccionesyrecomendaciones', 'recomendacion'],
    type: 'string',
  },
  {
    key: 'fechaSeguimiento',
    label: 'Fecha de Próximo Seguimiento',
    required: false,
    description: 'Fecha de control médico programada',
    synonyms: ['proximocontrol', 'seguimiento', 'fechavencimiento', 'fechaseguimiento', 'controlmedico'],
    type: 'date',
  },
  {
    key: 'peso',
    label: 'Peso (Kg)',
    required: false,
    description: 'Peso corporal del trabajador en kilogramos',
    synonyms: ['pesokg', 'pesocorporal', 'kg'],
    type: 'string',
  },
  {
    key: 'talla',
    label: 'Talla / Estatura (cm o m)',
    required: false,
    description: 'Estatura en centímetros o metros',
    synonyms: ['estatura', 'altura', 'cm', 'tallacm'],
    type: 'string',
  },
  {
    key: 'imc',
    label: 'Índice de Masa Corporal (IMC)',
    required: false,
    description: 'Valor o clasificación del IMC',
    synonyms: ['indicemasacorporal', 'masacorporal'],
    type: 'string',
  },
  {
    key: 'presionArterial',
    label: 'Presión Arterial (Tensión)',
    required: false,
    description: 'Cifras de tensión arterial (ej. 120/80)',
    synonyms: ['tension', 'tensionarterial', 'ta', 'pa'],
    type: 'string',
  },
  {
    key: 'frecuenciaCardiaca',
    label: 'Frecuencia Cardíaca (lpm)',
    required: false,
    description: 'Pulsaciones por minuto',
    synonyms: ['pulso', 'fc', 'latidos'],
    type: 'string',
  },
  {
    key: 'limitacionesBiomecanicas',
    label: 'Limitaciones Biomecánicas',
    required: false,
    description: 'Restricciones posturales, de carga o movimientos repetitivos',
    synonyms: ['limitacion', 'biomecanica', 'ergonomia', 'restriccionbiomecanica'],
    type: 'string',
  },
  {
    key: 'alergiasQuimicas',
    label: 'Alergias o Sustancias Químicas',
    required: false,
    description: 'Alergias a fármacos, látex, químicos u otros',
    synonyms: ['alergias', 'alergia', 'reacciones'],
    type: 'string',
  },
  {
    key: 'enfermedades',
    label: 'Enfermedades Comunes / Antecedentes',
    required: false,
    description: 'Hipertensión, diabetes u otras patologías crónicas',
    synonyms: ['antecedentespatologicos', 'enfermedadesprevias', 'patologias'],
    type: 'string',
  },
  {
    key: 'medicamentos',
    label: 'Medicamentos Habituales',
    required: false,
    description: 'Tratamientos farmacológicos actuales',
    synonyms: ['medicacion', 'farmacos', 'tratamiento'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma? (Hábito Tabaquismo)',
    required: false,
    description: 'Consumo de cigarrillo o tabaco (Sí / No)',
    synonyms: ['tabaquismo', 'fumador', 'cigarrillo'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
  {
    key: 'deporte',
    label: 'Actividad Física / Deporte',
    required: false,
    description: 'Frecuencia o tipo de ejercicio físico',
    synonyms: ['actividadfisica', 'ejercicio', 'practicadeporte', 'deporte'],
    type: 'string',
  },
  {
    key: 'alimentacion',
    label: 'Hábito de Alimentación',
    required: false,
    description: 'Dieta balanceada o hábitos nutricionales',
    synonyms: ['alimentacion', 'nutricion', 'dieta', 'habitosalimenticios'],
    type: 'string',
  },
  {
    key: 'riesgoCardiovascular',
    label: 'Riesgo Cardiovascular (Framingham)',
    required: false,
    description: 'Clasificación de riesgo cardiovascular (Bajo, Medio, Alto)',
    synonyms: ['riesgocardiovascular', 'rcv', 'framingham', 'cardiovascular'],
    type: 'string',
  },
  {
    key: 'terapiaPsicologica',
    label: 'Terapia Psicológica / Apoyo Psicosocial',
    required: false,
    description: 'Acompañamiento psicológico o psicosocial (Sí/No)',
    synonyms: ['terapiapsicologica', 'psicologia', 'apoyopsicosocial', 'saludmental'],
    type: 'string',
  },
  {
    key: 'fechaCursoAlturasAutorizado',
    label: 'Fecha Curso Alturas Trabajador Autorizado',
    required: false,
    description: 'Certificación vigente de trabajo en alturas',
    synonyms: ['cursoalturas', 'fechacursoalturas', 'alturasautorizado', 'fechacursoalturasautorizado'],
    type: 'date',
  },
  {
    key: 'fechaCursoAlturasCoordinador',
    label: 'Fecha Curso Coordinador de Alturas',
    required: false,
    description: 'Certificación de coordinador de trabajo en alturas',
    synonyms: ['coordinadoralturas', 'fechacursoalturascoordinador'],
    type: 'date',
  },
  {
    key: 'estadoLaboral',
    label: 'Estado Laboral (Activo / Retirado)',
    required: false,
    description: 'Situación laboral actual',
    synonyms: ['estadolaboral', 'estado', 'condicionlaboral', 'activo'],
    type: 'string',
  },
];

// ─── 3. Perfiles de Cargo ────────────────────────────────────────────────────
export const PERFILES_CARGO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombreCargo',
    label: 'Nombre del Cargo',
    required: true,
    description: 'Denominación oficial del cargo o puesto',
    synonyms: ['cargo', 'puesto', 'nombrepuesto', 'titulocargo', 'denominacion', 'puestodetrabajo', 'nombredelcargo', 'cargos'],
    type: 'string',
  },
  {
    key: 'area',
    label: 'Área / Departamento',
    required: false,
    description: 'Proceso, gerencia o departamento al que pertenece',
    synonyms: ['departamento', 'proceso', 'seccion', 'gerencia', 'unidad', 'area', 'areadetrabajo', 'areadeproceso'],
    type: 'string',
  },
  {
    key: 'nivelCargo',
    label: 'Nivel Jerárquico',
    required: false,
    description: 'Directivo, Mando Medio, Profesional, Operativo, Asistencial',
    synonyms: ['nivelcargo', 'jerarquia', 'clasificacioncargo', 'niveldelcargo', 'niveljerarquico', 'rangocargo'],
    type: 'string',
  },
  {
    key: 'sectorOrganizacion',
    label: 'Sector Organización',
    required: false,
    description: 'Sector privado, Sector público o Mixto',
    synonyms: ['sector', 'sectororganizacion', 'tipoempresa', 'sectorempresa'],
    type: 'string',
  },
  {
    key: 'jefeInmediato',
    label: 'Jefe Inmediato',
    required: false,
    description: 'Cargo a quien reporta directamente',
    synonyms: ['superiorsupervisor', 'reportaa', 'jefe', 'supervisor', 'jefeinmediato', 'superiorsinmediato'],
    type: 'string',
  },
  {
    key: 'tipoContrato',
    label: 'Tipo de Contrato / Vinculación',
    required: false,
    description: 'Indefinido, Fijo, Obra o labor, Prestación de servicios, etc.',
    synonyms: ['contrato', 'modalidadcontrato', 'tipodecontratacion', 'tipodevinculacion', 'vinculacion', 'tipocontrato'],
    type: 'string',
  },
  {
    key: 'jornada',
    label: 'Jornada Laboral',
    required: false,
    description: 'Tiempo completo, Turnos rotativos, Medio tiempo',
    synonyms: ['horario', 'turnos', 'jornada', 'jornadalaboral', 'horariodetrabajo'],
    type: 'string',
  },
  {
    key: 'escalasSalarial',
    label: 'Rango / Escala Salarial',
    required: false,
    description: 'Rango de remuneración económica',
    synonyms: ['salario', 'sueldo', 'escalasalarial', 'remuneracion', 'escalasalarial', 'basico', 'asignacionsalarial'],
    type: 'string',
  },
  {
    key: 'numVacantes',
    label: 'Número de Personas en el Cargo',
    required: false,
    description: 'Cantidad de personas o vacantes asociadas',
    synonyms: ['vacantes', 'plazas', 'personas', 'cupos', 'cantidadtrabajadores', 'numerodevacantes', 'nodevacantes', 'numvacantes', 'cantidadcolaboradores'],
    type: 'string',
  },
  {
    key: 'exigenciaFisica',
    label: 'Exigencia Física',
    required: false,
    description: 'Demanda física y biomecánica (cargas, posturas, bipedestación)',
    synonyms: ['exigenciafisica', 'demandafisica', 'esfuerzofisico', 'demandabiomecanica'],
    type: 'string',
  },
  {
    key: 'exigenciaMental',
    label: 'Exigencia Mental / Psicosocial',
    required: false,
    description: 'Concentración, atención, toma de decisiones o estrés',
    synonyms: ['exigenciamental', 'demandamental', 'cargamental', 'demandapsicosocial'],
    type: 'string',
  },
  {
    key: 'operaMaquinaria',
    label: '¿Opera Maquinaria o Equipos Críticos?',
    required: false,
    description: 'Operación de vehículos, maquinaria pesada, calderas, herramientas de potencia (Sí/No)',
    synonyms: ['operamaquinaria', 'maquinaria', 'conducevehiculo', 'operadordemaquinaria', 'equiposcriticos'],
    type: 'string',
  },
  {
    key: 'contextoAdicional',
    label: 'Misión / Descripción del Cargo',
    required: false,
    description: 'Propósito principal, funciones y contexto del puesto',
    synonyms: ['mision', 'objetivo', 'funciones', 'proposito', 'descripcion', 'descripciondetallada', 'contextoadicional', 'perfilprofesional', 'responsabilidades'],
    type: 'string',
  },
  {
    key: 'eppSeleccionados',
    label: 'Elementos de Protección Personal (EPP)',
    required: false,
    description: 'Listado de EPP requeridos para el cargo',
    synonyms: ['epp', 'epprequeridos', 'elementosdeproteccionpersonal', 'proteccionpersonal', 'epps', 'dotacionepp'],
    type: 'string',
  },
  {
    key: 'entrenamientosSeleccionados',
    label: 'Capacitaciones y Entrenamientos',
    required: false,
    description: 'Cursos obligatorios (alturas, espacios confinados, SST)',
    synonyms: ['entrenamientos', 'capacitaciones', 'cursos', 'formacion', 'entrenamientosrequeridos', 'capacitacionrequerida', 'competencias'],
    type: 'string',
  },
  {
    key: 'controlesFuenteSeleccionados',
    label: 'Controles en la Fuente',
    required: false,
    description: 'Controles existentes en la fuente del riesgo para este cargo',
    synonyms: ['controlesfuente', 'controlfuente', 'controlesenlafuente', 'fuente'],
    type: 'string',
  },
  {
    key: 'controlesMedioSeleccionados',
    label: 'Controles en el Medio',
    required: false,
    description: 'Controles existentes en el medio o ambiente laboral para este cargo',
    synonyms: ['controlesmedio', 'controlmedio', 'controlesenelmedio', 'medio'],
    type: 'string',
  },
  {
    key: 'report',
    label: 'Informe / Perfil Técnico de Cargo',
    required: false,
    description: 'Informe técnico detallado o ficha descriptiva completa del puesto',
    synonyms: ['informe', 'perfil', 'report', 'fichatecnica', 'documentoperfil'],
    type: 'string',
  },
];

// ─── 4. Matriz IPEVR (GTC-45) ────────────────────────────────────────────────
export const MATRIZ_IPEVAR_FIELDS: TargetFieldDef[] = [
  {
    key: 'proceso',
    label: 'Proceso',
    required: false,
    defaultValue: 'Operativo',
    description: 'Proceso estratégico, misional o de apoyo',
    synonyms: ['macroproceso', 'procesoempresa', 'procesos'],
    type: 'string',
  },
  {
    key: 'zona',
    label: 'Zona / Lugar',
    required: false,
    description: 'Área física o locación donde se realiza la actividad',
    synonyms: ['lugar', 'area', 'ubicacion', 'sitio', 'zonalugar', 'instalacion', 'sede'],
    type: 'string',
  },
  {
    key: 'actividad',
    label: 'Actividad',
    required: true,
    description: 'Nombre de la actividad evaluada',
    synonyms: ['nombreactividad', 'labor', 'actividades', 'actividadevaluada'],
    type: 'string',
  },
  {
    key: 'tareas',
    label: 'Tareas Específicas',
    required: false,
    description: 'Detalle de las tareas que componen la actividad',
    synonyms: ['tarea', 'tareasespecificas', 'pasos', 'operaciones'],
    type: 'string',
  },
  {
    key: 'rutinaria',
    label: '¿Es Rutinaria? (Sí / No)',
    required: false,
    description: 'Frecuencia rutinaria de la labor',
    synonyms: ['rutina', 'esrutinaria', 'frecuente', 'rutinario', 'rutinariiosino', 'rutinariosino'],
    type: 'string',
  },
  {
    key: 'peligro_clasificacion',
    label: 'Clasificación del Peligro (GTC-45)',
    required: true,
    description: 'Biológico, Físico, Químico, Biomecánico, Psicosocial, Condiciones de seguridad, Fenómenos naturales',
    synonyms: ['clasificacion', 'tipopeligro', 'categoriapeligro', 'clasificacionpeligro', 'peligroclasificacion', 'clasificaciondelpeligro', 'clasificacionpeligros'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Peligro',
    required: true,
    description: 'Fuente, situación o acto con potencial de daño',
    synonyms: ['peligro', 'factorriesgo', 'riesgo', 'descripcionpeligro', 'descripciondelpeligro', 'peligrodescripcion', 'detallepeligro'],
    type: 'string',
  },
  {
    key: 'efectos_posibles',
    label: 'Efectos Posibles en la Salud',
    required: false,
    description: 'Lesiones, enfermedades o consecuencias para los trabajadores',
    synonyms: ['efectos', 'consecuencias', 'danos', 'efectossalud', 'efectosposibles', 'posiblesefectos', 'efectosposiblesenlasalud'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Rol Expuesto',
    required: false,
    description: 'Puesto de trabajo expuesto a este riesgo',
    synonyms: ['puestoexpuesto', 'cargos', 'ocupacion', 'cargo', 'puesto', 'actividadcargo', 'cargorolexpuesto'],
    type: 'string',
  },
  {
    key: 'controles_fuente',
    label: 'Controles en la Fuente',
    required: false,
    description: 'Controles existentes en el origen del peligro',
    synonyms: ['fuente', 'controlfuente', 'controlesfuente', 'controlesenlafuente'],
    type: 'string',
  },
  {
    key: 'controles_medio',
    label: 'Controles en el Medio',
    required: false,
    description: 'Controles existentes en la transmisión o ambiente',
    synonyms: ['medio', 'controlmedio', 'controlesmedio', 'controlesenelmedio'],
    type: 'string',
  },
  {
    key: 'controles_individuo',
    label: 'Controles en el Individuo / EPP',
    required: false,
    description: 'Controles en el trabajador (capacitación, EPP, procedimientos)',
    synonyms: ['individuo', 'trabajador', 'epp', 'controlindividuo', 'controlesindividuo', 'controlesenelindividuo', 'persona'],
    type: 'string',
  },
  {
    key: 'nd',
    label: 'Nivel de Deficiencia (ND)',
    required: false,
    description: 'Valores GTC-45: 10, 6, 2 o 0',
    synonyms: ['deficiencia', 'dificiencia', 'valordeficiencia', 'nd', 'niveldeficiencia', 'niveldedificiencia', 'niveldedeficiencia'],
    type: 'number',
  },
  {
    key: 'ne',
    label: 'Nivel de Exposición (NE)',
    required: false,
    description: 'Valores GTC-45: 4, 3, 2 o 1',
    synonyms: ['exposicion', 'valorexposicion', 'ne', 'nivelexposicion', 'niveldeexposicion'],
    type: 'number',
  },
  {
    key: 'nc',
    label: 'Nivel de Consecuencia (NC)',
    required: false,
    description: 'Valores GTC-45: 100, 60, 25 o 10',
    synonyms: ['consecuencia', 'valorconsecuencia', 'nc', 'nivelconsecuencia', 'niveldeconsecuencia'],
    type: 'number',
  },
  {
    key: 'medida_eliminacion',
    label: 'Medida de Eliminación',
    required: false,
    description: 'Medida propuesta para eliminar el peligro',
    synonyms: ['eliminacion', 'medidaeliminacion', 'eliminac'],
    type: 'string',
  },
  {
    key: 'medida_sustitucion',
    label: 'Medida de Sustitución',
    required: false,
    description: 'Medida propuesta para sustituir el peligro',
    synonyms: ['sustitucion', 'medidasustitucion', 'sustituc'],
    type: 'string',
  },
  {
    key: 'medida_ingenieria',
    label: 'Controles de Ingeniería',
    required: false,
    description: 'Medidas técnicas o de ingeniería propuestas',
    synonyms: ['ingenieria', 'controlingenieria', 'medidaingenieria', 'controlesdeingenieria', 'controloesdeingenieria'],
    type: 'string',
  },
  {
    key: 'medida_administrativa',
    label: 'Controles Administrativos',
    required: false,
    description: 'Procedimientos, señalización o capacitaciones propuestas',
    synonyms: ['administrativo', 'controladministrativo', 'medidaadministrativa', 'controlesadministrativos', 'senializacion'],
    type: 'string',
  },
  {
    key: 'medida_eppu',
    label: 'Medida de EPP / Equipos de Protección',
    required: false,
    description: 'Equipos de protección personal propuestos',
    synonyms: ['epppropuesto', 'medidaepp', 'medidaeppu', 'equiposdeproteccionpersonal', 'elementosdeproteccionpersonal', 'elementosdeprteccionpersonal', 'elementosdeprteccionpersona', 'prteccionpersonal', 'epp'],
    type: 'string',
  },
  {
    key: 'nro_expuestos',
    label: 'Número de Expuestos',
    required: false,
    description: 'Cantidad de personas expuestas al peligro',
    synonyms: ['expuestos', 'numeroexpuestos', 'nroexpuestos', 'cantidadexpuestos', 'ndeexpuestos', 'nodeexpuestos'],
    type: 'number',
  },
  {
    key: 'peor_consecuencia',
    label: 'Peor Consecuencia',
    required: false,
    description: 'Mayor daño previsible que puede ocasionar el peligro',
    synonyms: ['peorconsecuencia', 'consecuenciamayor'],
    type: 'string',
  },
  {
    key: 'requisito_legal',
    label: 'Requisito Legal Específico',
    required: false,
    description: 'Norma colombiana o técnica aplicable (ej. Res. 0312, Res. 2400)',
    synonyms: ['requisitolegal', 'normatividad', 'legal', 'requisitoslegales', 'existenciarequisitolegalesp'],
    type: 'string',
  },
  {
    key: 'np',
    label: 'Nivel de Probabilidad (NP)',
    required: false,
    description: 'Producto del ND x NE (GTC-45)',
    synonyms: ['np', 'nivelprobabilidad', 'valornp', 'probabilidad'],
    type: 'number',
  },
  {
    key: 'interpretacion_np',
    label: 'Interpretación del Nivel de Probabilidad',
    required: false,
    description: 'Muy Alto (MA), Alto (A), Medio (M), Bajo (B)',
    synonyms: ['interpretacionnp', 'significadonp', 'interpretacionprobabilidad'],
    type: 'string',
  },
  {
    key: 'nr',
    label: 'Nivel de Riesgo e Intervención (NR)',
    required: false,
    description: 'Producto de NP x NC (GTC-45)',
    synonyms: ['nr', 'nivelriesgo', 'valornr', 'riesgointervencion', 'puntajeriesgo'],
    type: 'number',
  },
  {
    key: 'interpretacion_nr',
    label: 'Interpretación del Nivel de Riesgo (I, II, III, IV)',
    required: false,
    description: 'Nivel I (Crítico/Grave), II (Alto), III (Medio), IV (Bajo)',
    synonyms: ['interpretacionnr', 'nivelintervencion', 'clasificacionnr', 'romanorn'],
    type: 'string',
  },
  {
    key: 'aceptabilidad',
    label: 'Aceptabilidad del Riesgo (GTC-45)',
    required: false,
    description: 'No Aceptable, Aceptable con control específico, Mejorable, Aceptable',
    synonyms: ['aceptabilidad', 'aceptabilidaddelriesgo', 'valoracionriesgo'],
    type: 'string',
  },
  {
    key: 'factores_reduccion',
    label: 'Factores de Reducción / Viabilidad',
    required: false,
    description: 'Viabilidad técnica y económica de los controles (Anexo E GTC-45)',
    synonyms: ['factoresreduccion', 'viabilidad', 'justificacioncontrol'],
    type: 'string',
  },
  {
    key: 'origen_reporte',
    label: 'Origen del Reporte / Inspección',
    required: false,
    description: 'Fuente o mecanismo de identificación técnica del peligro',
    synonyms: ['origenreporte', 'fuenteidentificacion', 'mecanismoidentificacion'],
    type: 'string',
  },
];

// ─── 5. Matriz PESV (Seguridad Vial - Res. 20223040040595) ───────────────────
export const MATRIZ_PESV_FIELDS: TargetFieldDef[] = [
  {
    key: 'grupo_trabajo',
    label: 'Clasificación Grupos de Trabajo / Área',
    required: false,
    defaultValue: 'General',
    description: 'Área operativa, administrativa, conductores propios o contratistas',
    synonyms: ['grupotrabajo', 'clasificaciongruposdetrabajo', 'clasificaciongrupostrabajo', 'grupodetrabajo', 'gruposdetrabajo', 'area', 'sede', 'proceso'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo del Colaborador / Ocupación',
    required: true,
    description: 'Cargo individual evaluado que realiza desplazamientos viales',
    synonyms: ['cargo', 'puesto', 'cargosindividuales', 'cargos', 'conductor', 'trabajador', 'colaborador', 'cargotrabajador'],
    type: 'string',
  },
  {
    key: 'tipo_desplazamiento',
    label: 'Tipo de Desplazamiento (Misional / In itinere)',
    required: false,
    description: 'Misional (durante la jornada laboral) o In Itinere (trayecto casa-trabajo-casa)',
    synonyms: ['tipodesplazamiento', 'desplazamiento', 'tipoviaje', 'misionalinitinere', 'modalidad', 'tipodedesplazamiento'],
    type: 'string',
  },
  {
    key: 'rol_via',
    label: 'Rol en la Vía (Actor Vial)',
    required: true,
    description: 'Conductor vehículo pesado, liviano, motocicleta, ciclista, pasajero, peatón',
    synonyms: ['rolvia', 'rolenlavia', 'actorvial', 'rol', 'tipoconductor', 'rolenlaviaactorvial', 'rolviaactorvial'],
    type: 'string',
  },
  {
    key: 'factor_riesgo',
    label: 'Factor de Riesgo Vial (ANSV)',
    required: true,
    description: 'Factor Humano, Factor Vehicular, Factor Infraestructura o Entorno/Otros',
    synonyms: ['factorriesgo', 'factorderiesgo', 'factor', 'clasificacionriesgovial', 'factores', 'factorderiesgovial', 'tipofactor'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Riesgo / Peligros Viales',
    required: true,
    description: 'Exceso de velocidad, microsueño, mal estado de la vía, fallas mecánicas, etc.',
    synonyms: ['peligros', 'peligro', 'descripcionpeligro', 'riesgovial', 'situacionvial', 'descripcion', 'peligrodescripcion', 'peligrosidentificados'],
    type: 'string',
  },
  {
    key: 'np_cualitativo',
    label: 'Nivel de Probabilidad (NP Cualitativo)',
    required: false,
    description: 'MUY PROBABLE, MEDIANAMENTE PROBABLE, PROBABLE, POCO PROBABLE, NO ES PROBABLE',
    synonyms: ['npcualitativo', 'nivelprobabilidad', 'probabilidad', 'niveldeprobabilidad', 'np', 'probabilidadcualitativa'],
    type: 'string',
  },
  {
    key: 'np_cuantitativo',
    label: 'NP Cuantitativo (1 a 5)',
    required: false,
    description: 'Valor numérico de 1 a 5 según la metodología ANSV 2022',
    synonyms: ['npcuantitativo', 'valornp', 'npnumero', 'probabilidadcuantitativa', 'valordeprobabilidad'],
    type: 'number',
  },
  {
    key: 'ne_cualitativo',
    label: 'Nivel de Exposición (NE Cualitativo)',
    required: false,
    description: 'CONSTANTE, FRECUENTE, OCASIONAL, ESPORÁDICO, MÍNIMA',
    synonyms: ['necualitativo', 'nivelexposicion', 'exposicion', 'niveldeexposicion', 'ne', 'exposicioncualitativa'],
    type: 'string',
  },
  {
    key: 'ne_cuantitativo',
    label: 'NE Cuantitativo (1 a 5)',
    required: false,
    description: 'Valor numérico de 1 a 5 de frecuencia en la vía',
    synonyms: ['necuantitativo', 'valorne', 'nenumero', 'exposicioncuantitativa', 'valordeexposicion'],
    type: 'number',
  },
  {
    key: 'nc_cualitativo',
    label: 'Nivel de Consecuencia (NC Cualitativo)',
    required: false,
    description: 'CRÍTICO, PELIGROSO, MODERADO, MARGINAL, INSIGNIFICANTE',
    synonyms: ['nccualitativo', 'nivelconsecuencia', 'consecuencia', 'niveldeconsecuencia', 'nc', 'consecuenciacualitativa'],
    type: 'string',
  },
  {
    key: 'nc_cuantitativo',
    label: 'NC Cuantitativo (1 a 5)',
    required: false,
    description: 'Valor numérico de 1 a 5 de severidad de daños o lesiones',
    synonyms: ['nccuantitativo', 'valornc', 'ncnumero', 'consecuenciacuantitativa', 'valordeconsecuencia'],
    type: 'number',
  },
  {
    key: 'calificacion',
    label: 'Calificación Total del Riesgo (NP+NE+NC)',
    required: false,
    description: 'Suma de los 3 factores (rango de 3 a 15)',
    synonyms: ['calificacion', 'calificaciontotal', 'puntajeriesgo', 'totalcalificacion', 'evaluacionriesgo', 'calificacionriesgovial'],
    type: 'number',
  },
  {
    key: 'nivel_riesgo',
    label: 'Nivel de Riesgo Interpretado',
    required: false,
    description: 'NIVEL DE RIESGO BAJO, MEDIO o MODERADO, ALTO o CRÍTICO',
    synonyms: ['nivelriesgo', 'nivelderiesgo', 'criticidad', 'interpretacion', 'interpretaciondelriesgo'],
    type: 'string',
  },
  {
    key: 'aceptabilidad',
    label: 'Aceptabilidad del Riesgo Vial',
    required: false,
    description: 'ACEPTABLE, ACEPTABLE CON CONTROL ESPECÍFICO, NO ACEPTABLE',
    synonyms: ['aceptabilidad', 'aceptabilidadriesgo', 'aceptabilidadderiesgo', 'valoracionriesgo'],
    type: 'string',
  },
  {
    key: 'controles_existentes_descripcion',
    label: 'Controles Existentes / Diagnóstico',
    required: false,
    description: 'Descripción de las medidas y controles actualmente implementados',
    synonyms: ['controlesexistentes', 'controlesexistentesdescripcion', 'interpretacioncontroles', 'diagnosticocontroles', 'controlesactuales', 'controlesexistentesdiagnostico'],
    type: 'string',
  },
  {
    key: 'controles_existentes_tipo',
    label: 'Tipo de Control Existente (Jerarquía)',
    required: false,
    description: 'INDIVIDUO, MEDIO, MEDIO-INDIVIDUO, VEHICULO, INFRAESTRUCTURA, Ninguno',
    synonyms: ['controlesexistentestipo', 'tipocontrol', 'tipodecontrol', 'tipocontrolexistente', 'tipodecontroles', 'controles'],
    type: 'string',
  },
  {
    key: 'tratamiento_accion',
    label: 'Acción de Tratamiento / Decisión',
    required: false,
    description: 'EVITARLO, ACEPTARLO, ELIMINAR LA FUENTE QUE OCASIONA, MODIFICAR LOS FACTORES DE EXPOSICION',
    synonyms: ['tratamientoaccion', 'tratamiento', 'acciontratamiento', 'acciondetratamiento', 'acciones', 'tratamientoaccion'],
    type: 'string',
  },
  {
    key: 'plan_accion_medio',
    label: 'Plan de Acción - MEDIO',
    required: false,
    description: 'Intervenciones en la vía, horarios de tránsito, clima y rutas seguras',
    synonyms: ['planaccionmedio', 'controlesmedio', 'plandemedio', 'medio', 'plandeaccionmedio'],
    type: 'string',
  },
  {
    key: 'plan_accion_vehiculo',
    label: 'Plan de Acción - VEHÍCULO',
    required: false,
    description: 'Mantenimientos preventivos, inspección preoperacional, equipamiento de seguridad',
    synonyms: ['planaccionvehiculo', 'controlesvehiculo', 'plandevehiculo', 'vehiculo', 'plandeaccionvehiculo'],
    type: 'string',
  },
  {
    key: 'plan_accion_individuo',
    label: 'Plan de Acción - INDIVIDUO',
    required: false,
    description: 'Capacitaciones de manejo defensivo, exámenes psicosensométricos, pruebas de alcoholimetría',
    synonyms: ['planaccionindividuo', 'controlesindividuo', 'cotrolesindividuo', 'plandeindividuo', 'individuo', 'persona', 'plandeaccionindividuo'],
    type: 'string',
  },
  {
    key: 'plan_accion_infraestructura',
    label: 'Plan de Acción - INFRAESTRUCTURA',
    required: false,
    description: 'Parqueaderos seguros, señalización interna, accesos peatonales protegidos',
    synonyms: ['planaccioninfraestructura', 'controlesinfraestructura', 'plandeinfraestructura', 'infraestructura', 'via', 'plandeaccioninfraestructura'],
    type: 'string',
  },
  {
    key: 'responsable',
    label: 'Responsable de la Implementación',
    required: false,
    description: 'Cargo o líder responsable de velar por la ejecución de la acción vial',
    synonyms: ['responsable', 'lider', 'encargado', 'responsablecontrol', 'asignadoa', 'responsablepesv'],
    type: 'string',
  },
  {
    key: 'fecha_programacion',
    label: 'Fecha de Programación / Plazo',
    required: false,
    description: 'Fecha límite o periodicidad de la acción preventiva (YYYY-MM-DD o Permanente)',
    synonyms: ['fechaprogramacion', 'fecha', 'fechaplaneada', 'periodicidad', 'plazo', 'fechalimite', 'fechaprogramada'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado de la Acción (PLANEADA / CERRADA / EN PROCESO / VENCIDA)',
    required: false,
    description: 'Situación de avance del plan de acción vial',
    synonyms: ['estado', 'status', 'fase', 'situacion', 'estadodelplan'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Notas de Seguimiento',
    required: false,
    description: 'Comentarios adicionales, trazabilidad o evidencias viales',
    synonyms: ['observaciones', 'observacion', 'notas', 'comentarios', 'detalle', 'trazabilidad'],
    type: 'string',
  },
];

// ─── 6. Matriz de Compatibilidad Química (Decreto 1496/2018 - SGA) ───────────
export const MATRIZ_COMPATIBILIDAD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Producto Químico / Comercial',
    required: true,
    description: 'Nombre comercial o técnico de la sustancia química almacenada',
    synonyms: ['nombre', 'producto', 'sustancia', 'quimico', 'reactivo', 'nombrecomercial', 'productoquimico', 'nombredelproducto'],
    type: 'string',
  },
  {
    key: 'fabricante',
    label: 'Fabricante / Proveedor',
    required: false,
    description: 'Nombre del fabricante, importador o distribuidor del químico',
    synonyms: ['fabricante', 'proveedor', 'marca', 'fabricanteproveedor', 'distribuidor', 'empresa'],
    type: 'string',
  },
  {
    key: 'estado_fisico',
    label: 'Estado Físico (Líquido / Sólido / Gas)',
    required: false,
    description: 'Fase de la materia en condiciones normales de almacenamiento',
    synonyms: ['estadofisico', 'estado', 'formafisica', 'fase'],
    type: 'string',
  },
  {
    key: 'clasificacion_onu',
    label: 'Clase de Peligro ONU / SGA',
    required: true,
    description: 'Clase 1 a 9 (ej. Clase 3: Líquidos Inflamables, Clase 8: Corrosivos, etc.)',
    synonyms: ['clasificaciononu', 'clasepeligro', 'clase', 'categoria', 'clasificacionpeligro', 'claseonu', 'peligroonu', 'clasedepeligroonu', 'clasificacion', 'clasedepeligro'],
    type: 'string',
  },
  {
    key: 'pictogramas_sga',
    label: 'Pictogramas SGA (GHS)',
    required: false,
    description: 'Pictogramas de peligro (inflamable, corrosivo, calavera, etc.)',
    synonyms: ['pictogramassga', 'pictogramas', 'sga', 'pictograma', 'simbolos', 'iconosga', 'simbologiasga'],
    type: 'string',
  },
  {
    key: 'cantidad_almacenada',
    label: 'Cantidad Almacenada / Capacidad',
    required: false,
    description: 'Volumen o peso en inventario (ej. 50 Galones, 200 Kg, 5 Cilindros)',
    synonyms: ['cantidadalmacenada', 'cantidad', 'volumen', 'peso', 'stock', 'capacidadalmacenada', 'cant'],
    type: 'string',
  },
  {
    key: 'ubicacion',
    label: 'Ubicación en Almacén / Bodega',
    required: false,
    description: 'Área física o estantería donde se encuentra almacenado',
    synonyms: ['ubicacion', 'area', 'bodega', 'estante', 'almacen', 'ubicacionenalmacen', 'sector', 'lugar', 'areaalmacenamiento'],
    type: 'string',
  },
  {
    key: 'tiene_fds',
    label: '¿Tiene Ficha de Datos de Seguridad (FDS)?',
    required: false,
    description: 'Sí / No si cuenta con la FDS de 16 secciones actualizada',
    synonyms: ['tienefds', 'fds', 'msds', 'fichaseguridad', 'fichadedatosdeseguridad', 'hojadeseguridad'],
    type: 'string',
  },
  {
    key: 'tiene_rotulo',
    label: '¿Tiene Rótulo / Etiqueta SGA?',
    required: false,
    description: 'Sí / No si el envase primario y secundario está debidamente rotulado',
    synonyms: ['tienerotulo', 'rotulo', 'etiqueta', 'rotulosga', 'etiquetasga', 'rotulado'],
    type: 'string',
  },
  {
    key: 'incompatibilidades',
    label: 'Sustancias Incompatibles',
    required: false,
    description: 'Productos o familias químicas con las que reacciona violentamente',
    synonyms: ['incompatibilidades', 'incompatible', 'incompatibilidad', 'sustanciasincompatibles', 'noreunircon', 'materialesincompatibles'],
    type: 'string',
  },
  {
    key: 'requisitos_almacenamiento',
    label: 'Requisitos de Almacenamiento y Segregación',
    required: false,
    description: 'Contención de derrames, gabinetes FM, ventilación, distancia mínima o extintores',
    synonyms: ['requisitosalmacenamiento', 'almacenamiento', 'segregacion', 'condicionesalmacenamiento', 'recomendaciones', 'medidasalmacenamiento'],
    type: 'string',
  },
  {
    key: 'casNumber',
    label: 'Número CAS',
    required: false,
    description: 'Código numérico de identificación del Chemical Abstracts Service',
    synonyms: ['cas', 'numerocas', 'casnumber', 'idcas'],
    type: 'string',
  },
  {
    key: 'formulaQuimica',
    label: 'Fórmula Química / Composición',
    required: false,
    description: 'Fórmula molecular o componentes activos principales',
    synonyms: ['formula', 'formulaquimica', 'composicion', 'ingredienteactivo'],
    type: 'string',
  },
  {
    key: 'temperaturaAlmacenamiento',
    label: 'Temperatura de Almacenamiento (°C)',
    required: false,
    description: 'Rango de temperatura seguro para el almacenamiento',
    synonyms: ['temperatura', 'temperaturaalmacenamiento', 'temp'],
    type: 'string',
  },
  {
    key: 'tipoEnvase',
    label: 'Tipo de Envase / Contenedor',
    required: false,
    description: 'Tambor metálico, caneca plástica, garrafa, frasco vidrio, cilindro',
    synonyms: ['envase', 'tipoenvase', 'recipiente', 'empaque', 'contenedor'],
    type: 'string',
  },
  {
    key: 'kitDerrame',
    label: 'Kit Antiderrame / Absorbente Requerido',
    required: false,
    description: 'Absorbente mineral, cordones oleofílicos, neutralizador',
    synonyms: ['kitderrame', 'absorbente', 'controlfugas', 'kitantiderrames'],
    type: 'string',
  },
  {
    key: 'fechaIngreso',
    label: 'Fecha de Ingreso al Almacén',
    required: false,
    description: 'Fecha de recepción o compra del químico',
    synonyms: ['fechaingreso', 'fechaalmacen', 'fecharecepcion'],
    type: 'date',
  },
  {
    key: 'fechaVencimientoFds',
    label: 'Fecha Vencimiento FDS (Hoja de Seguridad)',
    required: false,
    description: 'Fecha de revisión o actualización de la ficha de seguridad (máximo 5 años)',
    synonyms: ['fechavencimientofds', 'vencimientofds', 'actualizacionfds', 'fechafds'],
    type: 'date',
  },
];

// ─── 7. Matriz Legal SG-SST ──────────────────────────────────────────────────
export const MATRIZ_LEGAL_FIELDS: TargetFieldDef[] = [
  {
    key: 'norma',
    label: 'Norma / Ley / Decreto / Resolución',
    required: true,
    description: 'Denominación de la norma (ej. Resolución 0312 de 2019, Decreto 1072 de 2015, Ley 9 de 1979)',
    synonyms: ['norma', 'ley', 'decreto', 'resolucion', 'normativa', 'normatividad', 'codigonorma', 'disposicion'],
    type: 'string',
  },
  {
    key: 'articulo',
    label: 'Artículo / Numeral / Estándar',
    required: false,
    description: 'Artículo, parágrafo o estándar aplicable (ej. E1.1.1, Art. 2.2.4.6.15)',
    synonyms: ['articulo', 'art', 'numeral', 'paragrafo', 'estandar', 'seccion', 'numeralestandar'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción / Requerimiento Legal',
    required: true,
    description: 'Texto u obligación legal exigida por la norma',
    synonyms: ['descripcion', 'requerimiento', 'exigencia', 'descripcionnorma', 'obligacion', 'requisito', 'textoarticulo'],
    type: 'string',
  },
  {
    key: 'evidencia',
    label: 'Evidencia de Cumplimiento / Mecanismo',
    required: false,
    description: 'Documento, registro o mecanismo que demuestra la conformidad',
    synonyms: ['evidencia', 'mecanismocumplimiento', 'soporte', 'formacumplimiento', 'documentoevidencia', 'verificacion'],
    type: 'string',
  },
  {
    key: 'categoria',
    label: 'Categoría / Eje Temático',
    required: false,
    description: 'Clasificación o estándar general (ej. Recursos, Peligros, COPASST, Emergencias)',
    synonyms: ['categoria', 'tema', 'ejetematico', 'capitulo', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado de Cumplimiento',
    required: false,
    description: 'Cumple, No Cumple o No Aplica',
    synonyms: ['estado', 'estadocumplimiento', 'cumplimiento', 'calificacion', 'conformidad', 'cumple'],
    type: 'string',
  },
  {
    key: 'seguimiento',
    label: 'Notas de Seguimiento / Responsable',
    required: false,
    description: 'Plan de acción, responsable o justificación',
    synonyms: ['seguimiento', 'observaciones', 'responsable', 'notas', 'justificacion', 'plandeaccion'],
    type: 'string',
  },
];

// ─── 8. Entrega y Seguimiento de EPP ─────────────────────────────────────────
export const EPP_TRACKING_FIELDS: TargetFieldDef[] = [
  {
    key: 'identificacion',
    label: 'Identificación / Cédula del Trabajador',
    required: true,
    description: 'Cédula o documento de quien recibe el EPP',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'dni', 'nodeidentificacion'],
    type: 'string',
  },
  {
    key: 'nombreTrabajador',
    label: 'Nombre del Trabajador',
    required: true,
    description: 'Nombre y apellidos del colaborador asignado',
    synonyms: ['nombre', 'trabajador', 'colaborador', 'empleado', 'nombretrabajador', 'nombresyapellidos', 'nombres'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo del Trabajador',
    required: false,
    description: 'Puesto o cargo desempeñado',
    synonyms: ['cargo', 'puesto', 'ocupacion', 'oficio'],
    type: 'string',
  },
  {
    key: 'elemento',
    label: 'Nombre del Elemento / EPP',
    required: true,
    description: 'Casco dieléctrico, Guantes nitrilo, Botas de seguridad, Monogafas, etc.',
    synonyms: ['elemento', 'epp', 'nombreepp', 'elementodeproteccion', 'proteccion', 'producto', 'articulo', 'descripcion'],
    type: 'string',
  },
  {
    key: 'tipo',
    label: 'Tipo de EPP (Regular / Alturas)',
    required: false,
    description: 'Clasificación entre Regular y Alturas',
    synonyms: ['tipo', 'tipoepp', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'marca',
    label: 'Marca / Fabricante',
    required: false,
    description: 'Marca del fabricante del elemento',
    synonyms: ['marca', 'fabricante', 'marcaepp'],
    type: 'string',
  },
  {
    key: 'referencia',
    label: 'Referencia / Modelo',
    required: false,
    description: 'Modelo o referencia del elemento',
    synonyms: ['referencia', 'modelo', 'ref'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Lote / Código',
    required: false,
    description: 'Código de trazabilidad o número de serie',
    synonyms: ['serial', 'lote', 'codigo', 'cod', 'numeroserie'],
    type: 'string',
  },
  {
    key: 'cantidad',
    label: 'Cantidad Entregada',
    required: false,
    description: 'Número de unidades dotadas',
    synonyms: ['cantidad', 'cant', 'unidades', 'dotacion'],
    type: 'number',
  },
  {
    key: 'fechaEntrega',
    label: 'Fecha de Entrega',
    required: true,
    description: 'Fecha en que se suministró el elemento',
    synonyms: ['fechaentrega', 'fecha', 'fentrega', 'fechasuministro', 'dotadofecha'],
    type: 'date',
  },
  {
    key: 'fechaVencimiento',
    label: 'Fecha de Vencimiento / Reposición',
    required: false,
    description: 'Fecha límite de vida útil o reposición periódica',
    synonyms: ['fechavencimiento', 'fvencimiento', 'vencimiento', 'proximareposicion', 'cambiofechafutura'],
    type: 'date',
  },
  {
    key: 'estado',
    label: 'Estado del EPP',
    required: false,
    description: 'Entregado, Vigente, Inspección Requerida, Fuera de Servicio',
    synonyms: ['estado', 'situacion', 'condicion', 'estadofisico'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Motivo de Entrega',
    required: false,
    description: 'Dotación periódica, reposición por daño, pérdida, etc.',
    synonyms: ['observaciones', 'motivo', 'notas', 'comentarios', 'detalle'],
    type: 'string',
  },
  {
    key: 'talla',
    label: 'Talla / Tamaño',
    required: false,
    description: 'Talla de guantes, calzado, arnés, etc.',
    synonyms: ['talla', 'tamano', 'medida', 'size'],
    type: 'string',
  },
  {
    key: 'categoria',
    label: 'Categoría / Parte del Cuerpo Protegida',
    required: false,
    description: 'Cabeza, Ojos/Rostro, Auditiva, Respiratoria, Manos, Pies, Caídas',
    synonyms: ['categoria', 'categoriaproteccion', 'partedelcuerpo', 'proteccion'],
    type: 'string',
  },
  {
    key: 'fechaUltimaInspeccion',
    label: 'Fecha de Última Inspección',
    required: false,
    description: 'Fecha de la inspección preoperacional o periódica',
    synonyms: ['fechaultimainspeccion', 'ultimainspeccion', 'fechainspeccion'],
    type: 'date',
  },
  {
    key: 'fechaProximaInspeccion',
    label: 'Fecha de Próxima Inspección',
    required: false,
    description: 'Fecha límite de la siguiente revisión obligatoria',
    synonyms: ['fechaproximainspeccion', 'proximainspeccion', 'vencimientoinspeccion'],
    type: 'date',
  },
  {
    key: 'inspeccionadoPor',
    label: 'Inspector / Responsable de Inspección',
    required: false,
    description: 'Nombre del inspector o líder SST que verificó el estado',
    synonyms: ['inspeccionadopor', 'inspector', 'revisadopor'],
    type: 'string',
  },
  {
    key: 'resultadoInspeccion',
    label: 'Resultado Inspección (Aprobado / Rechazado)',
    required: false,
    description: 'Aprobado, Rechazado o N/A',
    synonyms: ['resultadoinspeccion', 'resultado', 'concepto'],
    type: 'string',
  },
  {
    key: 'costoUnitario',
    label: 'Costo Unitario ($)',
    required: false,
    description: 'Valor económico del elemento para costeo de dotación',
    synonyms: ['costo', 'valor', 'precio', 'costounitario', 'preciounitario'],
    type: 'number',
  },
];

// ─── 9. Hoja de Vida Equipos en Alturas (Res. 4272/2021) ──────────────────────
export const EQUIPOS_ALTURAS_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Equipo de Alturas',
    required: true,
    description: 'Arnés de cuerpo entero, Eslinga con absorbedor, Línea de vida, Mosquetón, Casco con barbuquejo, etc.',
    synonyms: ['equipo', 'nombre', 'nombreequipo', 'tipoequipo', 'elemento', 'descripcion'],
    type: 'string',
  },
  {
    key: 'marca',
    label: 'Marca / Fabricante',
    required: false,
    description: 'Marca fabricante (ej. MSA, 3M DBI-SALA, Petzl, SOSEGA, Armadura)',
    synonyms: ['marca', 'fabricante', 'brand'],
    type: 'string',
  },
  {
    key: 'referencia',
    label: 'Referencia / Modelo',
    required: false,
    description: 'Modelo de fábrica o código de referencia',
    synonyms: ['referencia', 'modelo', 'ref', 'model'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Lote / Código Único',
    required: true,
    description: 'Número de serie único de trazabilidad para inspección obligatoria',
    synonyms: ['serial', 'lote', 'codigo', 'numeroserie', 'serienumero', 'id', 'placa'],
    type: 'string',
  },
  {
    key: 'fechaFabricacion',
    label: 'Fecha de Fabricación',
    required: false,
    description: 'Fecha de elaboración según etiqueta técnica',
    synonyms: ['fechafabricacion', 'fabricacion', 'ffabricacion', 'anofabricacion'],
    type: 'date',
  },
  {
    key: 'fechaCompra',
    label: 'Fecha de Compra / Puesta en Servicio',
    required: false,
    description: 'Fecha en que entró en servicio en la empresa',
    synonyms: ['fechacompra', 'puestaservicio', 'fechapuestaservicio', 'ingreso', 'fechaingreso'],
    type: 'date',
  },
  {
    key: 'fechaUltimaInspeccion',
    label: 'Fecha de Última Inspección',
    required: false,
    description: 'Fecha de la inspección por persona calificada',
    synonyms: ['fechaultimainspeccion', 'ultimainspeccion', 'fechainspeccion', 'finspeccion'],
    type: 'date',
  },
  {
    key: 'fechaProximaInspeccion',
    label: 'Fecha de Próxima Inspección',
    required: false,
    description: 'Próxima revisión obligatoria (máximo anual)',
    synonyms: ['fechaproximainspeccion', 'proximainspeccion', 'fechasiguienterevision', 'vencimientoinspeccion'],
    type: 'date',
  },
  {
    key: 'inspeccionadoPor',
    label: 'Inspector / Persona Calificada',
    required: false,
    description: 'Nombre de la persona calificada que realizó la inspección',
    synonyms: ['inspeccionadopor', 'inspector', 'personacalificada', 'responsableinspeccion'],
    type: 'string',
  },
  {
    key: 'resultadoInspeccion',
    label: 'Resultado Inspección (Aprobado / Rechazado)',
    required: false,
    description: 'Aprobado, Rechazado o N/A',
    synonyms: ['resultadoinspeccion', 'resultado', 'concepto', 'dictamen'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado Operativo del Equipo',
    required: false,
    description: 'Vigente, Vencido, Requiere Inspección, Retirado',
    synonyms: ['estado', 'condicion', 'situacion', 'operatividad'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Criterios de Descarte',
    required: false,
    description: 'Desgaste en costuras, corrosión metálica, deformación o notas',
    synonyms: ['observaciones', 'notas', 'detalles', 'criteriosdescarte', 'comentarios'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Cédula del Trabajador Asignado',
    required: false,
    description: 'Cédula del colaborador custodio del equipo',
    synonyms: ['cedula', 'cc', 'documento', 'identificaciontrabajador'],
    type: 'string',
  },
  {
    key: 'nombreTrabajador',
    label: 'Nombre del Trabajador Asignado',
    required: false,
    description: 'Nombre del colaborador al que se le entregó el equipo',
    synonyms: ['trabajador', 'colaborador', 'asignadoa', 'custodio', 'nombretrabajador'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo del Trabajador',
    required: false,
    description: 'Cargo u ocupación del trabajador asignado',
    synonyms: ['cargo', 'puesto', 'oficio'],
    type: 'string',
  },
  {
    key: 'lote',
    label: 'Lote de Fabricación',
    required: false,
    description: 'Número de lote asignado por el fabricante',
    synonyms: ['lote', 'lot', 'batch'],
    type: 'string',
  },
  {
    key: 'normaCertificacion',
    label: 'Norma de Certificación Técnica',
    required: false,
    description: 'Estándar técnico de certificación (ANSI Z359, EN 361, NTC, OSHA)',
    synonyms: ['norma', 'certificacion', 'normacertificacion', 'estandar'],
    type: 'string',
  },
  {
    key: 'tipoEquipo',
    label: 'Tipo de Componente Contra Caídas',
    required: false,
    description: 'Arnés, Eslinga, Conector, Anclaje, Línea de vida, Freno',
    synonyms: ['tipoequipo', 'componente', 'claseequipo'],
    type: 'string',
  },
  {
    key: 'vidaUtilAnios',
    label: 'Vida Útil Estimada (Años)',
    required: false,
    description: 'Años máximos de servicio recomendados por el fabricante (típicamente 5 o 10 años)',
    synonyms: ['vidautil', 'vidautilanios', 'durabilidad'],
    type: 'number',
  },
];

// ─── 10. Inventario e Inspección de Equipos de Emergencia ─────────────────────
export const EQUIPOS_EMERGENCIA_FIELDS: TargetFieldDef[] = [
  {
    key: 'categoria',
    label: 'Tipo de Equipo / Recurso de Emergencia',
    required: true,
    description: 'Extintor Multipropósito ABC, Extintor Solkaflam, Extintor CO2, Botiquín Tipo A/B/C, Camilla Rígida, Lámpara de Emergencia, Alarma, etc.',
    synonyms: ['equipo', 'categoria', 'tipoequipo', 'recurso', 'descripcion', 'claseequipo', 'nombre'],
    type: 'string',
  },
  {
    key: 'capacidad',
    label: 'Capacidad / Especificación Técnica',
    required: false,
    description: '10 lbs, 20 lbs, 3700 gr, Dotación NTC 4198, 180 kg, 2 horas de autonomía, etc.',
    synonyms: ['capacidad', 'especificacion', 'peso', 'tamano', 'medida', 'especificaciontecnica'],
    type: 'string',
  },
  {
    key: 'ubicacion',
    label: 'Ubicación Física / Área / Piso',
    required: true,
    description: 'Pasillo Principal, Recepción, Bodega de Químicos, Piso 2, Entrada Portería, etc.',
    synonyms: ['ubicacion', 'area', 'piso', 'lugar', 'sitio', 'sector', 'ubicacionfisica'],
    type: 'string',
  },
  {
    key: 'vencimiento',
    label: 'Fecha de Vencimiento / Próxima Recarga',
    required: true,
    description: 'Fecha límite de vigencia de la carga o de los insumos del botiquín',
    synonyms: ['vencimiento', 'fechavencimiento', 'proximarecarga', 'recarga', 'fecharecarga', 'fvencimiento'],
    type: 'date',
  },
  {
    key: 'estado',
    label: 'Estado Operativo del Recurso',
    required: false,
    description: 'Operativo, Recarga Pendiente, En Mantenimiento, Fuera de Servicio, Incompleto',
    synonyms: ['estado', 'condicion', 'situacion', 'operatividad', 'estadorecurso'],
    type: 'string',
  },
  {
    key: 'serial',
    label: 'Serial / Número de Placa / Identificador',
    required: false,
    description: 'Código de identificación física del extintor o botiquín',
    synonyms: ['serial', 'placa', 'id', 'numeroextintor', 'codigo', 'identificador'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Novedades de Inspección',
    required: false,
    description: 'Presión de manómetro, precinto de seguridad, señalización, soporte o notas',
    synonyms: ['observaciones', 'novedades', 'notas', 'inspeccion', 'comentarios'],
    type: 'string',
  },
  {
    key: 'marca',
    label: 'Marca / Fabricante',
    required: false,
    description: 'Marca del extintor o fabricante del equipo',
    synonyms: ['marca', 'fabricante', 'marcaextintor'],
    type: 'string',
  },
  {
    key: 'fechaRecarga',
    label: 'Fecha de Última Recarga',
    required: false,
    description: 'Fecha en que se realizó la última recarga o inspección hidroestática',
    synonyms: ['fecharecarga', 'ultimarecarga', 'fechaultimarecarga'],
    type: 'date',
  },
  {
    key: 'responsable',
    label: 'Responsable de Inspección / Custodio',
    required: false,
    description: 'Líder de brigada, inspector SST o proveedor técnico',
    synonyms: ['responsable', 'inspector', 'custodio', 'inspeccionadopor'],
    type: 'string',
  },
  {
    key: 'presion',
    label: 'Presión de Manómetro (Operativo / Bajo / Alto)',
    required: false,
    description: 'Estado de la aguja en el manómetro del extintor',
    synonyms: ['presion', 'manometro', 'presionmanometro'],
    type: 'string',
  },
  {
    key: 'senializacion',
    label: '¿Tiene Señalización Reflectiva? (Sí / No)',
    required: false,
    description: 'Señalización de extintor / camilla / botiquín visible y reglamentaria',
    synonyms: ['senializacion', 'senalizacion', 'senal', 'senaletica'],
    type: 'string',
  },
  {
    key: 'accesoDespejado',
    label: '¿Acceso Despejado? (Sí / No)',
    required: false,
    description: 'Área libre de obstáculos para acceso inmediato en emergencias',
    synonyms: ['accesodespejado', 'despejado', 'sinobstaculos', 'acceso'],
    type: 'string',
  },
];

// ─── 11. Programa de Capacitación en SG-SST ──────────────────────────────────
export const PROGRAMA_CAPACITACION_FIELDS: TargetFieldDef[] = [
  {
    key: 'tema',
    label: 'Tema de Capacitación',
    required: true,
    description: 'Inducción SG-SST, Manejo de Extintores, Trabajo Seguro en Alturas, Riesgo Biomecánico, Primeros Auxilios, etc.',
    synonyms: ['tema', 'capacitacion', 'nombrecapacitacion', 'actividad', 'curso', 'modulo', 'titulocapacitacion'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción / Objetivo / Alcance',
    required: false,
    description: 'Objetivo de aprendizaje o contenido de la sesión',
    synonyms: ['descripcion', 'objetivo', 'alcance', 'temario', 'detalles', 'contenido'],
    type: 'string',
  },
  {
    key: 'fecha',
    label: 'Fecha Programada',
    required: true,
    description: 'Fecha de ejecución o planeación (YYYY-MM-DD)',
    synonyms: ['fecha', 'fechaprogramada', 'fechasesion', 'diacapacitacion', 'fechaplaneada'],
    type: 'date',
  },
  {
    key: 'hora',
    label: 'Hora de Inicio',
    required: false,
    description: 'Hora de inicio de la sesión (ej. 08:00 AM, 14:00)',
    synonyms: ['hora', 'horainicio', 'horario'],
    type: 'string',
  },
  {
    key: 'duracion',
    label: 'Duración (Horas)',
    required: false,
    description: 'Intensidad horaria (ej. 1 hora, 2 horas, 4 horas)',
    synonyms: ['duracion', 'intensidad', 'horas', 'duracionhoras', 'intensidadhoraria'],
    type: 'string',
  },
  {
    key: 'responsable',
    label: 'Responsable / Facilitador / Entidad',
    required: false,
    description: 'ARL, Profesional SST, Bomberos, Entrenador SENA, etc.',
    synonyms: ['responsable', 'facilitador', 'capacitador', 'entidad', 'instructor', 'docente'],
    type: 'string',
  },
  {
    key: 'estado',
    label: 'Estado de la Capacitación',
    required: false,
    description: 'Programada, Ejecutada / Completada, Cancelada, Reprogramada',
    synonyms: ['estado', 'situacion', 'condicion', 'cumplimiento'],
    type: 'string',
  },
  {
    key: 'publicoObjetivo',
    label: 'Público Objetivo / Población Convocada',
    required: false,
    description: 'Todo el personal, Personal operativo, Brigadistas, Miembros COPASST, etc.',
    synonyms: ['publico', 'poblacion', 'cargos', 'asistentes', 'destinatarios', 'publicoobjetivo'],
    type: 'string',
  },
  {
    key: 'modalidad',
    label: 'Modalidad (Presencial / Virtual / Híbrida)',
    required: false,
    description: 'Metodología de entrega de la formación',
    synonyms: ['modalidad', 'metodologia', 'tiposesion'],
    type: 'string',
  },
  {
    key: 'lugar',
    label: 'Lugar / Salón / Plataforma',
    required: false,
    description: 'Sala de juntas, auditorio, Teams, Zoom, etc.',
    synonyms: ['lugar', 'sitio', 'salon', 'ubicacion', 'link', 'plataforma'],
    type: 'string',
  },
  {
    key: 'asistentes',
    label: 'Número de Asistentes / Cupo',
    required: false,
    description: 'Cantidad de personas convocadas o registradas',
    synonyms: ['asistentes', 'cupo', 'participantes', 'cantidadasistentes'],
    type: 'number',
  },
  {
    key: 'evaluacion',
    label: '¿Requiere Evaluación de Eficacia? (Sí / No)',
    required: false,
    description: 'Si se aplica prueba de conocimientos o evaluación práctica',
    synonyms: ['evaluacion', 'evaluacionconocimiento', 'test', 'quiz', 'eficacia'],
    type: 'string',
  },
  {
    key: 'porcentajeAprobacion',
    label: 'Porcentaje de Aprobación Mínimo (%)',
    required: false,
    description: 'Calificación mínima exigida (ej. 80%)',
    synonyms: ['porcentajeaprobacion', 'calificacionminima', 'notaminima', 'aprobacion'],
    type: 'string',
  },
];

// ─── 12. Gestión Integral de Ausentismo y ATEL ────────────────────────────────
export const AUSENTISMO_FIELDS: TargetFieldDef[] = [
  {
    key: 'fecha',
    label: 'Fecha de Inicio de Incapacidad / Ausencia',
    required: true,
    description: 'Fecha desde la cual inicia el periodo de ausencia (YYYY-MM-DD)',
    synonyms: ['fechainicio', 'fecha', 'fechadesde', 'desde', 'iniciodescanso', 'fechaincapacidad'],
    type: 'date',
  },
  {
    key: 'fechaFin',
    label: 'Fecha de Fin de Incapacidad',
    required: false,
    description: 'Fecha final del descanso médico o permiso',
    synonyms: ['fechafin', 'fechahasta', 'hasta', 'findescanso', 'fechareintegro'],
    type: 'date',
  },
  {
    key: 'tipo',
    label: 'Tipo de Evento / Causa de Ausentismo',
    required: true,
    description: 'AT (Accidente Trabajo), EL (Enfermedad Laboral), EG_EPS (Enfermedad General), ACC_COMUN, LIC_MAT, LIC_PAT, LUTO, etc.',
    synonyms: ['tipo', 'tipoevento', 'causa', 'motivo', 'clasificacion', 'tiponovedad', 'origenincapacidad'],
    type: 'string',
  },
  {
    key: 'diasIncapacidad',
    label: 'Días de Incapacidad / Días Ausentes',
    required: true,
    description: 'Cantidad de días otorgados en la certificación médica',
    synonyms: ['dias', 'diasincapacidad', 'diasotorgados', 'diasausencia', 'cantidaddias', 'nrodias'],
    type: 'number',
  },
  {
    key: 'horasAusencia',
    label: 'Horas de Ausencia (si aplica)',
    required: false,
    description: 'Horas laborales perdidas para permisos o citas médicas',
    synonyms: ['horas', 'horasausencia', 'horasperdidas'],
    type: 'number',
  },
  {
    key: 'cie10',
    label: 'Código CIE-10 / Diagnóstico',
    required: false,
    description: 'Código alfanumérico CIE-10 (ej. M545 Lumbago, S934 Esguince de tobillo, J069)',
    synonyms: ['cie10', 'diagnostico', 'codigocie10', 'patologia', 'diagnosticoeps', 'cie'],
    type: 'string',
  },
  {
    key: 'descripcion',
    label: 'Descripción del Evento / Consecuencia',
    required: false,
    description: 'Detalle de la lesión, síntoma o motivo de la ausencia',
    synonyms: ['descripcion', 'detalle', 'consecuencia', 'observacion', 'diagnosticoescrito'],
    type: 'string',
  },
  {
    key: 'nombre',
    label: 'Nombre del Colaborador',
    required: true,
    description: 'Nombre completo del trabajador ausente',
    synonyms: ['nombre', 'trabajador', 'colaborador', 'empleado', 'nombresyapellidos', 'nombres'],
    type: 'string',
  },
  {
    key: 'cedula',
    label: 'Cédula / Documento de Identidad',
    required: false,
    description: 'Número de documento de identidad del trabajador',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'dni'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Puesto del Colaborador',
    required: false,
    description: 'Cargo desempeñado en la empresa',
    synonyms: ['cargo', 'puesto', 'ocupacion', 'oficio'],
    type: 'string',
  },
  {
    key: 'salario',
    label: 'Salario Base / IBC Mensual',
    required: false,
    description: 'Ingreso Base de Cotización para costeo financiero de ausentismo',
    synonyms: ['salario', 'sueldo', 'ibc', 'remuneracion', 'ibcmensual', 'salariobase'],
    type: 'number',
  },
  {
    key: 'entidad',
    label: 'Entidad de Salud (EPS / ARL)',
    required: false,
    description: 'Nombre de la EPS o ARL que emitió o cubre la incapacidad',
    synonyms: ['entidad', 'eps', 'arl', 'entidadsalud', 'aseguradora'],
    type: 'string',
  },
  {
    key: 'observaciones',
    label: 'Observaciones / Estado de Recobro',
    required: false,
    description: 'En trámite de cobro, reconocido, pagado, observaciones generales',
    synonyms: ['observaciones', 'recobro', 'notas', 'comentarios', 'tramiterecobro'],
    type: 'string',
  },
  {
    key: 'area',
    label: 'Área / Departamento / Sede',
    required: false,
    description: 'Área de trabajo del colaborador',
    synonyms: ['area', 'seccion', 'departamento', 'sede', 'proceso'],
    type: 'string',
  },
  {
    key: 'origen',
    label: 'Origen del Evento (Común / Laboral)',
    required: false,
    description: 'Origen Común o de Origen Laboral (ARL)',
    synonyms: ['origen', 'origenincapacidad', 'clasificacionorigen'],
    type: 'string',
  },
  {
    key: 'severidad',
    label: 'Severidad del Evento (Leve / Moderado / Grave)',
    required: false,
    description: 'Calificación de la gravedad médica del accidente o enfermedad',
    synonyms: ['severidad', 'gravedad', 'clasificaciongravedad'],
    type: 'string',
  },
  {
    key: 'parteCuerpo',
    label: 'Parte del Cuerpo Afectada',
    required: false,
    description: 'Región anatómica lesionada (manos, columna, miembros inferiores, etc.)',
    synonyms: ['partecuerpo', 'regionanatomica', 'zonacuerpo', 'miembroafectado'],
    type: 'string',
  },
  {
    key: 'mecanismoAccidente',
    label: 'Mecanismo del Accidente / Agente',
    required: false,
    description: 'Caída al mismo nivel, golpeado por, sobreesfuerzo, contacto eléctrico',
    synonyms: ['mecanismoaccidente', 'agente', 'formadelaccidente', 'mecanismo'],
    type: 'string',
  },
];

// ─── 13. Tablero Kanban ACPM (Acciones Correctivas, Preventivas y Mejora) ─────
export const KANBAN_ACPM_FIELDS: TargetFieldDef[] = [
  {
    key: 'title',
    label: 'Título de la Acción / Tarea ACPM',
    required: true,
    description: 'Nombre de la acción correctiva, preventiva, de mejora o compromiso',
    synonyms: ['actividad', 'tarea', 'titulo', 'nombre', 'accion', 'plandeaccion', 'compromiso', 'activity', 'title', 'nombretarea'],
    type: 'string',
  },
  {
    key: 'description',
    label: 'Descripción / Hallazgo / Causa Raíz',
    required: false,
    description: 'No conformidad identificada, causa raíz analizada o alcance del control',
    synonyms: ['descripcion', 'hallazgo', 'causaraiz', 'noconformidad', 'detalles', 'detalle', 'description', 'alcance'],
    type: 'string',
  },
  {
    key: 'dueDate',
    label: 'Fecha Límite / Fecha de Cierre',
    required: true,
    description: 'Fecha máxima para implementar y cerrar la acción (YYYY-MM-DD)',
    synonyms: ['fechalimite', 'fecha', 'vencimiento', 'fechacierre', 'duedate', 'fechaentrega', 'plazo', 'fechaprogramada'],
    type: 'date',
  },
  {
    key: 'status',
    label: 'Estado de la Tarea (todo / due_soon / overdue / done)',
    required: false,
    description: 'Por hacer (todo), Próxima a vencer (due_soon), Vencida (overdue) o Completada (done)',
    synonyms: ['estado', 'status', 'columna', 'situacion', 'fase'],
    type: 'string',
  },
  {
    key: 'actionType',
    label: 'Tipo de Acción ACPM (Correctiva / Preventiva / Mejora)',
    required: false,
    description: 'Clasificación de la acción según PHVA',
    synonyms: ['tipoaccion', 'acciontipo', 'acpm', 'tipoacpm', 'clasificacionaccion'],
    type: 'string',
  },
  {
    key: 'priority',
    label: 'Prioridad (Alta / Media / Baja)',
    required: false,
    description: 'Nivel de urgencia o criticidad del hallazgo',
    synonyms: ['prioridad', 'criticidad', 'urgencia', 'priority', 'severidad'],
    type: 'string',
  },
  {
    key: 'assignedTo',
    label: 'Responsable Asignado',
    required: false,
    description: 'Persona o cargo responsable de implementar y cerrar la tarea',
    synonyms: ['responsable', 'asignadoa', 'encargado', 'lider', 'assignedto', 'ejecutor'],
    type: 'string',
  },
  {
    key: 'sourceModule',
    label: 'Módulo de Origen / Fuente del Hallazgo',
    required: false,
    description: 'Auditoría, Inspección, COPASST, IPEVR, ATEL, PESV, etc.',
    synonyms: ['origen', 'fuente', 'sourcemodule', 'moduloorigen', 'procedencia'],
    type: 'string',
  },
];

// ─── 14. Análisis de Vulnerabilidad y Emergencias ─────────────────────────────
export const VULNERABILIDAD_FIELDS: TargetFieldDef[] = [
  {
    key: 'amenaza',
    label: 'Nombre de la Amenaza',
    required: true,
    description: 'Sismo, Inundación, Incendio, Fuga de gas, Derrame de químicos, Robo / Asalto, etc.',
    synonyms: ['amenaza', 'peligro', 'nombreamenaza', 'evento', 'eventoamenazante', 'riesgo'],
    type: 'string',
  },
  {
    key: 'origenAmenaza',
    label: 'Origen de la Amenaza (Natural / Tecnológico / Social)',
    required: false,
    description: 'Natural (Sismo, Inundación...), Tecnológico (Incendio, Derrame...) o Social (Robo, Atentado...)',
    synonyms: ['origen', 'origenamenaza', 'tipoamenaza', 'fuente', 'clasificacion'],
    type: 'string',
  },
  {
    key: 'nivelAmenaza',
    label: 'Calificación de la Amenaza (Posible / Probable / Inminente)',
    required: false,
    description: 'Nivel estimado de probabilidad o recurrencia',
    synonyms: ['nivel', 'nivelamenaza', 'calificacion', 'probabilidad', 'frecuencia'],
    type: 'string',
  },
  {
    key: 'descripcionGlobal',
    label: 'Descripción / Antecedentes de la Amenaza',
    required: false,
    description: 'Historial en la empresa, cercanías a fallas geológicas, ríos o zonas industriales',
    synonyms: ['descripcion', 'antecedentes', 'descripcionglobal', 'historial', 'observaciones'],
    type: 'string',
  },
  {
    key: 'medidasExistentes',
    label: 'Medidas de Prevención Existentes',
    required: false,
    description: 'Controles actuales (detectores de humo, brigada, rutas de evacuación, etc.)',
    synonyms: ['medidasexistentes', 'controles', 'medidasactuales', 'prevencion', 'controlesexistentes'],
    type: 'string',
  },
  {
    key: 'fuenteRiesgo',
    label: 'Fuente del Riesgo / Detonante',
    required: false,
    description: 'Factores internos o externos que detonan la amenaza',
    synonyms: ['fuenteriesgo', 'fuente', 'detonante', 'causaprincipal'],
    type: 'string',
  },
  {
    key: 'color',
    label: 'Color del Diamante (Verde / Amarillo / Rojo)',
    required: false,
    description: 'Verde (Posible), Amarillo (Probable), Rojo (Inminente)',
    synonyms: ['color', 'colordiamante', 'rombo', 'calificacioncolor'],
    type: 'string',
  },
  {
    key: 'personasAfectadas',
    label: 'Población Expuesta / Personas Afectadas',
    required: false,
    description: 'Número o grupo de trabajadores expuestos a la amenaza',
    synonyms: ['personasafectadas', 'poblacionexpuesta', 'afectados', 'ocupantes'],
    type: 'string',
  },
  {
    key: 'impactoEconomico',
    label: 'Impacto en la Operación y Bienes',
    required: false,
    description: 'Afectación estimada sobre infraestructura, inventario y continuidad del negocio',
    synonyms: ['impactoeconomico', 'impacto', 'danosmateriales', 'continuidadnegocio'],
    type: 'string',
  },
];

