/**
 * moduleFieldDefinitions.ts — Definiciones de campos oficiales para los aplicativos de WAPPY
 * Usado por el Mapeador Universal de Columnas (Paralelo de Casillas).
 */

import { TargetFieldDef } from './columnMapperEngine';

// ─── 1. Perfil Sociodemográfico ──────────────────────────────────────────────
export const SOCIODEMOGRAFICO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre Completo',
    required: true,
    description: 'Nombres y apellidos completos del trabajador',
    synonyms: ['nombres', 'apellidos', 'nombrecompleto', 'colaborador', 'empleado', 'trabajador', 'nombresyapellidos', 'apellidosynombres'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Número de Identificación / Cédula',
    required: true,
    description: 'Cédula de ciudadanía, extranjería, PEP o PPT',
    synonyms: ['cedula', 'cc', 'documento', 'identificacion', 'numeroidentificacion', 'numerocedula', 'dni', 'nodeidentificacion', 'nodedocumento', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Puesto de Trabajo',
    required: false,
    description: 'Cargo actual desempeñado en la empresa',
    synonyms: ['puesto', 'ocupacion', 'oficio', 'cargotrabajador', 'puestotrabajo', 'cargoactual'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino, Femenino u Otro',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaNacimiento',
    label: 'Fecha de Nacimiento',
    required: false,
    description: 'Formato YYYY-MM-DD o DD/MM/AAAA',
    synonyms: ['fnacimiento', 'fechanac', 'fechanacimiento', 'cumpleanos', 'natalicio'],
    type: 'date',
  },
  {
    key: 'estadoCivil',
    label: 'Estado Civil',
    required: false,
    description: 'Soltero, Casado, Unión libre, Separado, Viudo',
    synonyms: ['estadocivil', 'estadocivilactual'],
    type: 'string',
  },
  {
    key: 'nivelEscolaridad',
    label: 'Nivel de Escolaridad',
    required: false,
    description: 'Primaria, Bachiller, Técnico, Tecnólogo, Profesional, Posgrado',
    synonyms: ['escolaridad', 'estudios', 'gradoinstruccion', 'nivelacademico', 'titulacion'],
    type: 'string',
  },
  {
    key: 'telefono',
    label: 'Teléfono / Celular',
    required: false,
    description: 'Número de contacto móvil o fijo',
    synonyms: ['celular', 'tel', 'movil', 'telefonofijo', 'numerocelular', 'contacto'],
    type: 'string',
  },
  {
    key: 'correoElectronico',
    label: 'Correo Electrónico',
    required: false,
    description: 'Email corporativo o personal',
    synonyms: ['email', 'correo', 'mail', 'correopersonal', 'correocorporativo'],
    type: 'string',
  },
  {
    key: 'direccion',
    label: 'Dirección de Residencia',
    required: false,
    description: 'Dirección física de domicilio',
    synonyms: ['domicilio', 'residencia', 'direcciondomicilio'],
    type: 'string',
  },
  {
    key: 'barrio',
    label: 'Barrio',
    required: false,
    description: 'Barrio de residencia',
    synonyms: ['sector', 'barrioresidencia'],
    type: 'string',
  },
  {
    key: 'municipioDomicilio',
    label: 'Municipio / Ciudad',
    required: false,
    description: 'Ciudad de residencia habitual',
    synonyms: ['ciudad', 'municipio', 'poblacion'],
    type: 'string',
  },
  {
    key: 'estrato',
    label: 'Estrato Socioeconómico',
    required: false,
    description: 'Estrato de 1 a 6',
    synonyms: ['estratosocioeconomico'],
    type: 'string',
  },
  {
    key: 'vivienda',
    label: 'Tipo de Vivienda',
    required: false,
    description: 'Propia, Arrendada, Familiar, etc.',
    synonyms: ['tipovivienda', 'tenenciavivienda'],
    type: 'string',
  },
  {
    key: 'personasCargo',
    label: 'Personas a Cargo / Hijos',
    required: false,
    description: 'Cantidad de personas dependientes',
    synonyms: ['hijos', 'personascargo', 'dependientes', 'numhijos', 'numerohijos'],
    type: 'number',
  },
  {
    key: 'salario',
    label: 'Salario / Remuneración',
    required: false,
    description: 'Salario base o rango salarial',
    synonyms: ['sueldo', 'remuneracion', 'salariobasico', 'ingresos'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma?',
    required: false,
    description: 'Hábito de tabaquismo (Sí / No)',
    synonyms: ['fumador', 'cigarrillo', 'tabaco', 'consumotabaco'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'deporte',
    label: 'Actividad Física / Deporte',
    required: false,
    description: 'Frecuencia o tipo de ejercicio físico',
    synonyms: ['actividadfisica', 'ejercicio', 'practicadeporte'],
    type: 'string',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnósticos Médicos Previos',
    required: false,
    description: 'Antecedentes o patologías diagnosticadas',
    synonyms: ['diagnostico', 'patologia', 'enfermedades', 'antecedentes'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha Último Examen Médico',
    required: false,
    description: 'Fecha de valoración médica ocupacional',
    synonyms: ['fechaexamen', 'fechamedico', 'ultimoexamen', 'examenocupacional'],
    type: 'date',
  },
];

// ─── 2. Condiciones de Salud ────────────────────────────────────────────────
export const CONDICIONES_SALUD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre',
    label: 'Nombre del Trabajador',
    required: true,
    description: 'Nombre y apellidos del colaborador',
    synonyms: ['trabajador', 'colaborador', 'empleado', 'nombresyapellidos', 'nombrecompleto', 'nombres', 'apellidos'],
    type: 'string',
  },
  {
    key: 'identificacion',
    label: 'Identificación / Cédula',
    required: true,
    description: 'Número de documento de identidad',
    synonyms: ['cedula', 'cc', 'documento', 'numeroidentificacion', 'dni', 'nodeidentificacion', 'nodecedula'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo',
    required: false,
    description: 'Cargo u ocupación evaluada',
    synonyms: ['puesto', 'oficio', 'cargotrabajador', 'puestotrabajo'],
    type: 'string',
  },
  {
    key: 'edad',
    label: 'Edad',
    required: false,
    description: 'Edad en años cumplidos',
    synonyms: ['anios', 'anos', 'edadaniversario'],
    type: 'number',
  },
  {
    key: 'genero',
    label: 'Género / Sexo',
    required: false,
    description: 'Masculino o Femenino',
    synonyms: ['sexo', 'generotrabajador'],
    type: 'string',
  },
  {
    key: 'fechaExamenMedico',
    label: 'Fecha del Examen Médico',
    required: false,
    description: 'Fecha en que se practicó la evaluación ocupacional',
    synonyms: ['fecha', 'fechavaloracion', 'fechamedica', 'fechaexamen', 'fechadelexamen', 'ultimoexamen'],
    type: 'date',
  },
  {
    key: 'diagnosticoMedico',
    label: 'Diagnóstico Médico (CIE-10)',
    required: false,
    description: 'Código CIE-10 o descripción médica del diagnóstico',
    synonyms: ['diagnostico', 'cie10', 'patologia', 'hallazgo', 'enfermedad', 'diagnosticoprincipal', 'conceptomedico'],
    type: 'string',
  },
  {
    key: 'recomendacionesMedicas',
    label: 'Recomendaciones y Restricciones',
    required: false,
    description: 'Medidas médico-laborales preventivas, restricciones o correctivas',
    synonyms: ['restricciones', 'recomendaciones', 'medidas', 'indicaciones', 'restriccionesyrecomendaciones', 'recomendacion'],
    type: 'string',
  },
  {
    key: 'fechaSeguimiento',
    label: 'Fecha de Próximo Seguimiento',
    required: false,
    description: 'Fecha de control médico programada',
    synonyms: ['proximocontrol', 'seguimiento', 'fechavencimiento', 'fechaseguimiento', 'controlmedico'],
    type: 'date',
  },
  {
    key: 'peso',
    label: 'Peso (Kg)',
    required: false,
    description: 'Peso corporal del trabajador en kilogramos',
    synonyms: ['pesokg', 'pesocorporal', 'kg'],
    type: 'string',
  },
  {
    key: 'talla',
    label: 'Talla / Estatura (cm o m)',
    required: false,
    description: 'Estatura en centímetros o metros',
    synonyms: ['estatura', 'altura', 'cm', 'tallacm'],
    type: 'string',
  },
  {
    key: 'imc',
    label: 'Índice de Masa Corporal (IMC)',
    required: false,
    description: 'Valor o clasificación del IMC',
    synonyms: ['indicemasacorporal', 'masacorporal'],
    type: 'string',
  },
  {
    key: 'presionArterial',
    label: 'Presión Arterial (Tensión)',
    required: false,
    description: 'Cifras de tensión arterial (ej. 120/80)',
    synonyms: ['tension', 'tensionarterial', 'ta', 'pa'],
    type: 'string',
  },
  {
    key: 'frecuenciaCardiaca',
    label: 'Frecuencia Cardíaca (lpm)',
    required: false,
    description: 'Pulsaciones por minuto',
    synonyms: ['pulso', 'fc', 'latidos'],
    type: 'string',
  },
  {
    key: 'limitacionesBiomecanicas',
    label: 'Limitaciones Biomecánicas',
    required: false,
    description: 'Restricciones posturales, de carga o movimientos repetitivos',
    synonyms: ['limitacion', 'biomecanica', 'ergonomia', 'restriccionbiomecanica'],
    type: 'string',
  },
  {
    key: 'alergiasQuimicas',
    label: 'Alergias o Sustancias Químicas',
    required: false,
    description: 'Alergias a fármacos, látex, químicos u otros',
    synonyms: ['alergias', 'alergia', 'reacciones'],
    type: 'string',
  },
  {
    key: 'enfermedades',
    label: 'Enfermedades Comunes / Antecedentes',
    required: false,
    description: 'Hipertensión, diabetes u otras patologías crónicas',
    synonyms: ['antecedentespatologicos', 'enfermedadesprevias', 'patologias'],
    type: 'string',
  },
  {
    key: 'medicamentos',
    label: 'Medicamentos Habituales',
    required: false,
    description: 'Tratamientos farmacológicos actuales',
    synonyms: ['medicacion', 'farmacos', 'tratamiento'],
    type: 'string',
  },
  {
    key: 'fuma',
    label: '¿Fuma? (Hábito Tabaquismo)',
    required: false,
    description: 'Consumo de cigarrillo o tabaco (Sí / No)',
    synonyms: ['tabaquismo', 'fumador', 'cigarrillo'],
    type: 'string',
  },
  {
    key: 'alcohol',
    label: 'Consumo de Alcohol',
    required: false,
    description: 'Frecuencia de consumo de bebidas alcohólicas',
    synonyms: ['licor', 'bebidasalcoholicas', 'consumoalcohol'],
    type: 'string',
  },
  {
    key: 'eps',
    label: 'EPS',
    required: false,
    description: 'Entidad Promotora de Salud',
    synonyms: ['entidadpromotoradesalud', 'epsactual', 'salud'],
    type: 'string',
  },
  {
    key: 'afp',
    label: 'Fondo de Pensiones (AFP)',
    required: false,
    description: 'Fondo de pensiones y cesantías',
    synonyms: ['pension', 'fondopension', 'pensiones', 'fondodepensiones'],
    type: 'string',
  },
];

// ─── 3. Perfiles de Cargo ────────────────────────────────────────────────────
export const PERFILES_CARGO_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombreCargo',
    label: 'Nombre del Cargo',
    required: true,
    description: 'Denominación oficial del cargo o puesto',
    synonyms: ['cargo', 'puesto', 'nombrepuesto', 'titulocargo', 'denominacion', 'puestodetrabajo', 'nombredelcargo'],
    type: 'string',
  },
  {
    key: 'area',
    label: 'Área / Departamento',
    required: false,
    description: 'Proceso, gerencia o departamento al que pertenece',
    synonyms: ['departamento', 'proceso', 'seccion', 'gerencia', 'unidad', 'area'],
    type: 'string',
  },
  {
    key: 'nivelCargo',
    label: 'Nivel Jerárquico',
    required: false,
    description: 'Directivo, Mando Medio, Profesional, Operativo, Asistencial',
    synonyms: ['nivel', 'jerarquia', 'clasificacioncargo', 'niveldelcargo'],
    type: 'string',
  },
  {
    key: 'jefeInmediato',
    label: 'Jefe Inmediato',
    required: false,
    description: 'Cargo a quien reporta directamente',
    synonyms: ['superiorsupervisor', 'reportaa', 'jefe', 'supervisor', 'jefeinmediato'],
    type: 'string',
  },
  {
    key: 'tipoContrato',
    label: 'Tipo de Contrato / Vinculación',
    required: false,
    description: 'Indefinido, Fijo, Obra o labor, Prestación de servicios',
    synonyms: ['contrato', 'modalidadcontrato', 'tipodecontratacion', 'tipodevinculacion', 'vinculacion'],
    type: 'string',
  },
  {
    key: 'jornada',
    label: 'Jornada Laboral',
    required: false,
    description: 'Tiempo completo, Turnos rotativos, Medio tiempo',
    synonyms: ['horario', 'turnos', 'jornada', 'jornadalaboral'],
    type: 'string',
  },
  {
    key: 'escalasSalarial',
    label: 'Rango / Escala Salarial',
    required: false,
    description: 'Rango de remuneración económica',
    synonyms: ['salario', 'sueldo', 'escalasalarial', 'remuneracion', 'escalasalarial'],
    type: 'string',
  },
  {
    key: 'numVacantes',
    label: 'Número de Personas en el Cargo',
    required: false,
    description: 'Cantidad de personas o vacantes asociadas',
    synonyms: ['vacantes', 'plazas', 'personas', 'cupos', 'cantidadtrabajadores', 'numerodevacantes', 'nodevacantes'],
    type: 'string',
  },
  {
    key: 'contextoAdicional',
    label: 'Misión / Descripción del Cargo',
    required: false,
    description: 'Propósito principal, funciones y contexto del puesto',
    synonyms: ['mision', 'objetivo', 'funciones', 'proposito', 'descripcion', 'descripciondetallada', 'contextoadicional'],
    type: 'string',
  },
  {
    key: 'eppSeleccionados',
    label: 'Elementos de Protección Personal (EPP)',
    required: false,
    description: 'Listado de EPP requeridos para el cargo',
    synonyms: ['epp', 'epprequeridos', 'elementosdeproteccionpersonal', 'proteccionpersonal', 'epps'],
    type: 'string',
  },
  {
    key: 'entrenamientosSeleccionados',
    label: 'Capacitaciones y Entrenamientos',
    required: false,
    description: 'Cursos obligatorios (alturas, espacios confinados, SST)',
    synonyms: ['entrenamientos', 'capacitaciones', 'cursos', 'formacion', 'entrenamientosrequeridos'],
    type: 'string',
  },
  {
    key: 'exigenciaFisica',
    label: 'Exigencia Física',
    required: false,
    description: 'Demanda física y biomecánica (cargas, posturas, bipedestación)',
    synonyms: ['exigenciafisica', 'demandafisica', 'esfuerzofisico'],
    type: 'string',
  },
  {
    key: 'exigenciaMental',
    label: 'Exigencia Mental / Psicosocial',
    required: false,
    description: 'Concentración, atención, toma de decisiones o estrés',
    synonyms: ['exigenciamental', 'demandamental', 'cargamental'],
    type: 'string',
  },
];

// ─── 4. Matriz IPEVR (GTC-45) ────────────────────────────────────────────────
export const MATRIZ_IPEVAR_FIELDS: TargetFieldDef[] = [
  {
    key: 'proceso',
    label: 'Proceso',
    required: true,
    description: 'Proceso estratégico, misional o de apoyo',
    synonyms: ['macroproceso', 'procesoempresa'],
    type: 'string',
  },
  {
    key: 'zona',
    label: 'Zona / Lugar',
    required: false,
    description: 'Área física o locación donde se realiza la actividad',
    synonyms: ['lugar', 'area', 'ubicacion', 'sitio', 'zonalugar'],
    type: 'string',
  },
  {
    key: 'actividad',
    label: 'Actividad',
    required: true,
    description: 'Nombre de la actividad evaluada',
    synonyms: ['nombreactividad', 'labor'],
    type: 'string',
  },
  {
    key: 'tareas',
    label: 'Tareas Específicas',
    required: false,
    description: 'Detalle de las tareas que componen la actividad',
    synonyms: ['tarea', 'tareasespecificas', 'pasos'],
    type: 'string',
  },
  {
    key: 'rutinaria',
    label: '¿Es Rutinaria? (Sí / No)',
    required: false,
    description: 'Frecuencia rutinaria de la labor',
    synonyms: ['rutina', 'esrutinaria', 'frecuente'],
    type: 'string',
  },
  {
    key: 'peligro_clasificacion',
    label: 'Clasificación del Peligro (GTC-45)',
    required: true,
    description: 'Biológico, Físico, Químico, Biomecánico, Psicosocial, Condiciones de seguridad, Fenómenos naturales',
    synonyms: ['clasificacion', 'tipopeligro', 'categoriapeligro', 'clasificacionpeligro'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Peligro',
    required: true,
    description: 'Fuente, situación o acto con potencial de daño',
    synonyms: ['peligro', 'factorriesgo', 'riesgo', 'descripcionpeligro', 'descripciondelpeligro'],
    type: 'string',
  },
  {
    key: 'efectos_posibles',
    label: 'Efectos Posibles en la Salud',
    required: false,
    description: 'Lesiones, enfermedades o consecuencias para los trabajadores',
    synonyms: ['efectos', 'consecuencias', 'danos', 'efectossalud', 'efectosposibles'],
    type: 'string',
  },
  {
    key: 'cargo',
    label: 'Cargo / Rol Expuesto',
    required: false,
    description: 'Puesto de trabajo expuesto a este riesgo',
    synonyms: ['puestoexpuesto', 'cargos', 'ocupacion', 'cargo'],
    type: 'string',
  },
  {
    key: 'controles_fuente',
    label: 'Controles en la Fuente',
    required: false,
    description: 'Controles existentes en el origen del peligro',
    synonyms: ['fuente', 'controlfuente', 'controlesfuente'],
    type: 'string',
  },
  {
    key: 'controles_medio',
    label: 'Controles en el Medio',
    required: false,
    description: 'Controles existentes en la transmisión o ambiente',
    synonyms: ['medio', 'controlmedio', 'controlesmedio'],
    type: 'string',
  },
  {
    key: 'controles_individuo',
    label: 'Controles en el Individuo / EPP',
    required: false,
    description: 'Controles en el trabajador (capacitación, EPP, procedimientos)',
    synonyms: ['individuo', 'trabajador', 'epp', 'controlindividuo', 'controlesindividuo'],
    type: 'string',
  },
  {
    key: 'nd',
    label: 'Nivel de Deficiencia (ND)',
    required: false,
    description: 'Valores GTC-45: 10, 6, 2 o 0',
    synonyms: ['deficiencia', 'valordeficiencia', 'nd'],
    type: 'number',
  },
  {
    key: 'ne',
    label: 'Nivel de Exposición (NE)',
    required: false,
    description: 'Valores GTC-45: 4, 3, 2 o 1',
    synonyms: ['exposicion', 'valorexposicion', 'ne'],
    type: 'number',
  },
  {
    key: 'nc',
    label: 'Nivel de Consecuencia (NC)',
    required: false,
    description: 'Valores GTC-45: 100, 60, 25 o 10',
    synonyms: ['consecuencia', 'valorconsecuencia', 'nc'],
    type: 'number',
  },
  {
    key: 'medida_eliminacion',
    label: 'Medida de Eliminación',
    required: false,
    description: 'Medida propuesta para eliminar el peligro',
    synonyms: ['eliminacion', 'medidaeliminacion'],
    type: 'string',
  },
  {
    key: 'medida_sustitucion',
    label: 'Medida de Sustitución',
    required: false,
    description: 'Medida propuesta para sustituir el peligro',
    synonyms: ['sustitucion', 'medidasustitucion'],
    type: 'string',
  },
  {
    key: 'medida_ingenieria',
    label: 'Controles de Ingeniería',
    required: false,
    description: 'Medidas técnicas o de ingeniería propuestas',
    synonyms: ['ingenieria', 'controlingenieria', 'medidaingenieria'],
    type: 'string',
  },
  {
    key: 'medida_administrativa',
    label: 'Controles Administrativos',
    required: false,
    description: 'Procedimientos, señalización o capacitaciones propuestas',
    synonyms: ['administrativo', 'controladministrativo', 'medidaadministrativa', 'senializacion'],
    type: 'string',
  },
  {
    key: 'medida_eppu',
    label: 'Medida de EPP / Equipos de Protección',
    required: false,
    description: 'Equipos de protección personal propuestos',
    synonyms: ['epppropuesto', 'medidaepp', 'medidaeppu'],
    type: 'string',
  },
  {
    key: 'nro_expuestos',
    label: 'Número de Expuestos',
    required: false,
    description: 'Cantidad de personas expuestas al peligro',
    synonyms: ['expuestos', 'numeroexpuestos', 'nroexpuestos', 'cantidadexpuestos'],
    type: 'number',
  },
  {
    key: 'peor_consecuencia',
    label: 'Peor Consecuencia',
    required: false,
    description: 'Mayor daño previsible que puede ocasionar el peligro',
    synonyms: ['peorconsecuencia', 'consecuenciamayor'],
    type: 'string',
  },
  {
    key: 'requisito_legal',
    label: 'Requisito Legal Específico',
    required: false,
    description: 'Norma colombiana o técnica aplicable (ej. Res. 0312, Res. 2400)',
    synonyms: ['requisitolegal', 'normatividad', 'legal'],
    type: 'string',
  },
];

// ─── 5. Matriz PESV (Seguridad Vial) ─────────────────────────────────────────
export const MATRIZ_PESV_FIELDS: TargetFieldDef[] = [
  {
    key: 'cargo',
    label: 'Cargo del Colaborador',
    required: true,
    description: 'Cargo que realiza desplazamientos viales',
    synonyms: ['puesto', 'conductor', 'trabajador', 'cargotrabajador'],
    type: 'string',
  },
  {
    key: 'rol_via',
    label: 'Rol en la Vía (Actor Vial)',
    required: true,
    description: 'Conductor vehículo pesado, liviano, moto, bicicleta, peatón',
    synonyms: ['actorvial', 'rolvia', 'rol', 'tipoconductor'],
    type: 'string',
  },
  {
    key: 'tipo_desplazamiento',
    label: 'Tipo de Desplazamiento',
    required: false,
    description: 'Misional (durante la jornada) o In Itinere (casa-trabajo-casa)',
    synonyms: ['desplazamiento', 'tipoviaje', 'misionalinitinere'],
    type: 'string',
  },
  {
    key: 'factor_riesgo',
    label: 'Factor de Riesgo Vial',
    required: true,
    description: 'Factor Humano, Factor Vehicular, Factor Infraestructura o Entorno',
    synonyms: ['factor', 'clasificacionriesgovial', 'tipofactor'],
    type: 'string',
  },
  {
    key: 'peligro_descripcion',
    label: 'Descripción del Riesgo Vial',
    required: true,
    description: 'Exceso de velocidad, microsueño, estado de la vía, etc.',
    synonyms: ['peligro', 'riesgovial', 'situacionvial'],
    type: 'string',
  },
  {
    key: 'responsable',
    label: 'Responsable del Control',
    required: false,
    description: 'Cargo o persona encargada de la intervención',
    synonyms: ['responsablecontrol', 'lider'],
    type: 'string',
  },
];

// ─── 6. Matriz de Compatibilidad Química ─────────────────────────────────────
export const MATRIZ_COMPATIBILIDAD_FIELDS: TargetFieldDef[] = [
  {
    key: 'nombre_comercial',
    label: 'Nombre Comercial / Producto Químico',
    required: true,
    description: 'Nombre del producto químico o sustancia almacenada',
    synonyms: ['producto', 'sustancia', 'quimico', 'reactivo', 'nombre'],
    type: 'string',
  },
  {
    key: 'numero_un',
    label: 'Número ONU (UN)',
    required: false,
    description: 'Código de 4 dígitos de Naciones Unidas (ej. UN 1203)',
    synonyms: ['un', 'onu', 'numeroun', 'codigoun', 'identificadoronu'],
    type: 'string',
  },
  {
    key: 'clase_peligro',
    label: 'Clase de Peligro Principal (SGA / ONU)',
    required: true,
    description: 'Clase de 1 a 9 (ej. Líquidos inflamables, Corrosivos, etc.)',
    synonyms: ['clase', 'categoria', 'clasificacionpeligro', 'claseonu'],
    type: 'string',
  },
  {
    key: 'estado_fisico',
    label: 'Estado Físico',
    required: false,
    description: 'Líquido, Sólido o Gas',
    synonyms: ['estado', 'formafisica'],
    type: 'string',
  },
  {
    key: 'area_almacenamiento',
    label: 'Área / Bodega de Almacenamiento',
    required: false,
    description: 'Ubicación física en la planta o bodega',
    synonyms: ['bodega', 'almacen', 'estante', 'ubicacion'],
    type: 'string',
  },
];
